const REDIRECTS=new Map([
  ["/aaja","/"],["/astro","/tools/astro"],["/my-diary","/me/diary"],["/notes","/me/notes"],["/planner","/me/planner"],["/family","/me/family"],["/family/join","/me/family"],["/tools/family","/me/family"],["/tithi","/me/reminders"],["/settings/notifications","/me/reminders"],["/tools/tithi","/me/reminders"],["/card","/me/cards"],["/tools/card","/me/cards"],["/settings","/me/settings"],["/settings/holidays","/me/settings"],["/my-data","/me/data"],["/tools/my-data","/me/data"],["/diaspora","/tools/clock"],["/jyotish/rashifal","/rashifal"],["/jyotish/china/rashi","/rashifal"],["/jyotish/janma-patro","/jyotish/china"]
]);
const SPA_EXACT=new Set(["/","/tools","/tools/astro","/me","/convert","/rashifal","/samachar","/fm","/tv","/time-machine","/on-this-day","/jyotish/china","/jyotish/matchmaking","/about","/sources","/privacy","/terms","/contact","/developers","/offline","/explore"]);
function clean(p){return !p||p==="/"?"/":p.replace(/\/+$/,"")||"/"}
function spaPath(p){return SPA_EXACT.has(p)||/^\/calendar\/\d{4}\/\d{1,2}$/.test(p)||p.startsWith("/me/")||p.startsWith("/tools/")||p.startsWith("/jyotish/")||p.startsWith("/date/")||p.startsWith("/festival/")}
function workerPath(p){return p==="/api"||p.startsWith("/api/")||p==="/fm-v2-stream"||p.startsWith("/fm-v2-stream/")||p==="/fm-stream"||p.startsWith("/fm-stream/")}
function communityPath(p){return p==="/samudaya"||p.startsWith("/samudaya/")||p.startsWith("/nepal-sambat/mandala")}
export function routeMode(input){const p=clean(input);if(REDIRECTS.has(p)||p.startsWith("/family/"))return"redirect";if(workerPath(p))return"worker";if(spaPath(p)||communityPath(p))return"static";const leaf=p.split("/").pop()||"";if(leaf.includes("."))return"static";return"not_found"}
function missingBinding(){return new Response(JSON.stringify({error:"patro_api_service_binding_missing",hint:"Bind PATRO_API to Worker service 'patro' in the Pages project."}),{status:503,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function notFound(){return new Response("<!doctype html><html lang=\"ne\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width\"><title>पृष्ठ भेटिएन · आफ्नै पात्रो</title><body style=\"font-family:system-ui,sans-serif;padding:3rem;text-align:center\"><h1>४०४ · पृष्ठ भेटिएन</h1><p>तपाईंले खोज्नुभएको ठेगाना उपलब्ध छैन।</p><p><a href=\"/\">पात्रोमा जानुहोस्</a> · <a href=\"/tools\">उपकरण हेर्नुहोस्</a></p></body></html>",{status:404,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})}
export const onRequest=async({request,env,next})=>{const url=new URL(request.url),path=clean(url.pathname),mode=routeMode(path);if(mode==="redirect"){const dest=REDIRECTS.get(path)||"/me/family";url.pathname=dest;return Response.redirect(url.toString(),301)}if(mode==="worker"){if(!env.PATRO_API||typeof env.PATRO_API.fetch!=="function")return missingBinding();return env.PATRO_API.fetch(request)}if(mode==="static")return next();return notFound()};
