import { z } from "npm:zod@4.1.12";
import * as Astronomy from "npm:astronomy-engine@2.1.19";
import { devanagariToTirhuta } from "../community-engine/tirhuta.ts";
import { devanagariToLimbu } from "../community-engine/limbu.ts";
import { devanagariToNewa } from "../community-engine/newa-script.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"", SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const DAY=86400000, SUITES=["lhosar","tharu","mithila","kirat","hijri"] as const, COMMUNITY_IDS=["nepal-sambat",...SUITES] as const;
const META:any={lhosar:{dev:"ल्होसार",en:"Lhosar"},tharu:{dev:"थारु",en:"Tharu"},mithila:{dev:"मिथिला",en:"Mithila"},kirat:{dev:"किरात",en:"Kirat"},hijri:{dev:"हिजरी",en:"Hijri / Muslim"}};
const DATE=/^\d{4}-\d{2}-\d{2}$/; const CACHE="public, max-age=60, s-maxage=3600, stale-while-revalidate=86400", DAYCACHE="public, max-age=300, s-maxage=86400, stale-while-revalidate=604800";
function h(){return{apikey:SERVICE_KEY,authorization:"Bearer "+SERVICE_KEY,"content-type":"application/json"}}
function j(body:any,status=200,headers:any={}){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}})}
function bad(error:string,detail?:any){return j({ok:false,error,detail},400,{"cache-control":"no-store"})}
function iso(d:Date){return d.toISOString().slice(0,10)} function add(d:string,n:number){const x=new Date(d+"T00:00:00Z");x.setUTCDate(x.getUTCDate()+n);return iso(x)}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function valid(d:string){if(!DATE.test(d))return false;const x=new Date(d+"T00:00:00Z");return !Number.isNaN(x.getTime())&&iso(x)===d}
async function db(path:string,init:RequestInit={}){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error("missing_supabase_runtime_secrets");const r=await fetch(SUPABASE_URL+"/rest/v1/"+path,{...init,headers:{...h(),...(init.headers||{})},signal:AbortSignal.timeout(8000)});if(!r.ok)throw new Error("database_request_failed:"+r.status+":"+(await r.text()).slice(0,240));const t=await r.text();return t?JSON.parse(t):null}
function e(s:string){return encodeURIComponent(s)} function badge(c:string){return c==="announced"||c==="confirmed"?"घोषित":c==="expected"?"सम्भावित":"गणना"}
function icsEsc(s:string){return String(s).replace(/\\/g,"\\\\").replace(/;/g,"\\;").replace(/,/g,"\\,").replace(/\n/g,"\\n")} function icsDate(s:string){return s.replaceAll("-","")}

type F={suite:string;id:string;dev:string;roman?:string;en?:string;communities?:string[];summary?:string;holiday?:string;status:string;sources?:string[];places?:string[];details?:string[]};
type D={suite:string;festival_id:string;region?:string|null;year:number;main:string;start_ad:string;end_ad:string;confidence:string};
type O={suite:string;festival_id:string;year:number;start_ad:string;end_ad?:string|null;note?:string|null};
async function fmap(s:string){const rows=await db("community_festivals?suite=eq."+e(s)+"&select=*") as F[];return new Map(rows.map(r=>[r.id,r]))}
async function ovs(s:string,years:number[]){const y=[...new Set(years)];if(!y.length)return[] as O[];const q=y.length===1?"year=eq."+y[0]:"year=in.("+y.join(",")+")";return await db("community_overrides?suite=eq."+e(s)+"&"+q+"&select=*") as O[]}
function merge(rows:D[],fm:Map<string,F>,os:O[]){const om=new Map(os.map(o=>[o.festival_id+"|"+o.year,o]));return rows.map(r=>{const f=fm.get(r.festival_id),o=!r.region?om.get(r.festival_id+"|"+r.year):undefined,c=o?"announced":r.confidence;return{id:r.festival_id,dev:f?.dev||r.festival_id,roman:f?.roman||null,en:f?.en||null,region:r.region||null,main:o?.start_ad||r.main,start:o?.start_ad||r.start_ad,end:o?.end_ad||o?.start_ad||r.end_ad,confidence:c,badge:badge(c),holiday:f?.holiday||"none",summary:f?.summary||"",communities:f?.communities||[],places:f?.places||[],details:f?.details||[],status:f?.status||"review",review:f?.status==="review",review_label:f?.status==="review"?"समीक्षाधीन":null,sources:f?.sources||[],override_note:o?.note||null}})}

const CQ=z.object({year:z.coerce.number().int().min(2020).max(2050).optional(),from:z.string().regex(DATE).optional(),count:z.coerce.number().int().min(1).max(50).default(10)}).strict();
export async function communityItems(suite:string,sp:URLSearchParams,internal=false){if(!SUITES.includes(suite as any))return j({ok:false,error:"unknown_suite"},404,{"cache-control":"no-store"});const q=CQ.safeParse(Object.fromEntries(sp));if(!q.success)return bad("invalid_query",q.error.flatten());const fm=await fmap(suite);let rows:D[]=[];if(q.data.year)rows=await db("community_dates?suite=eq."+e(suite)+"&year=eq."+q.data.year+"&select=*&order=start_ad.asc,festival_id.asc") as D[];else{const from=q.data.from||today(),to=add(from,370);rows=await db("community_dates?suite=eq."+e(suite)+"&start_ad=gte."+from+"&start_ad=lte."+to+"&select=*&order=start_ad.asc&limit="+Math.max(q.data.count*4,30)) as D[];rows=rows.filter(x=>!x.region).slice(0,q.data.count)}const os=await ovs(suite,rows.map(x=>x.year)),items=merge(rows,fm,os);return j({ok:true,suite:{id:suite,...META[suite]},items,review:items.filter((x:any)=>x.review).map((x:any)=>({id:x.id,dev:x.dev})),source:"engine-generated database; official overrides layered at request time"},200,{"cache-control":internal?"no-store":CACHE})}
export async function listCommunities(){const out:any[]=[];for(const s of SUITES){const r=await communityItems(s,new URLSearchParams({from:today(),count:"1"}),true),p=await r.json();out.push({id:s,...META[s],next:p.items?.[0]||null})}return j({ok:true,communitySuite:{dev:"समुदाय",en:"Community Suite"},suites:[{id:"nepal-sambat",dev:"नेपाल संवत्",en:"Nepal Sambat"},...out]},200,{"cache-control":CACHE})}
export async function communityIcs(suite:string,sp:URLSearchParams){const year=Number(sp.get("year")||new Date().getUTCFullYear());if(!Number.isInteger(year)||year<2020||year>2050)return bad("invalid_year");const r=await communityItems(suite,new URLSearchParams({year:String(year)}),true);if(r.status!==200)return r;const p=await r.json(),lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Mero Patro//Community Suite//NE","CALSCALE:GREGORIAN","X-WR-CALNAME:"+icsEsc(p.suite.dev+" · "+p.suite.en),"REFRESH-INTERVAL;VALUE=DURATION:P7D"];for(const x of p.items)lines.push("BEGIN:VEVENT","UID:"+x.id+"-"+x.start+"@meropatro","DTSTART;VALUE=DATE:"+icsDate(x.start),"DTEND;VALUE=DATE:"+icsDate(add(x.end,1)),"SUMMARY:"+icsEsc(x.dev+" · "+x.en),"DESCRIPTION:"+icsEsc(x.badge+(x.review?" · समीक्षाधीन":"")+" · "+x.summary),"END:VEVENT");lines.push("END:VCALENDAR");return new Response(lines.join("\r\n")+"\r\n",{headers:{"content-type":"text/calendar; charset=utf-8","cache-control":DAYCACHE}})}
export async function combinedCommunityIcs(req:Request){const u=new URL(req.url);let ids=(u.searchParams.get("communities")||"").split(",").filter(Boolean).filter(x=>COMMUNITY_IDS.includes(x as any));if(!ids.length)ids=[...COMMUNITY_IDS];const from=u.searchParams.get("from")||today();if(!valid(from))return bad("invalid_from");const to=add(from,550),lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Mero Patro//My Communities//NE","CALSCALE:GREGORIAN","X-WR-CALNAME:मेरो समुदाय · Mero Patro","REFRESH-INTERVAL;VALUE=DURATION:P1D"];for(const s of ids.filter(x=>x!=="nepal-sambat")){const rows=await db("community_dates?suite=eq."+e(s)+"&region=is.null&start_ad=gte."+from+"&start_ad=lte."+to+"&select=*&order=start_ad.asc") as D[],fm=await fmap(s),os=await ovs(s,rows.map(x=>x.year));for(const x of merge(rows,fm,os))lines.push("BEGIN:VEVENT","UID:"+s+"-"+x.id+"-"+x.start+"@meropatro","DTSTART;VALUE=DATE:"+icsDate(x.start),"DTEND;VALUE=DATE:"+icsDate(add(x.end,1)),"SUMMARY:"+icsEsc(x.dev+" · "+x.en),"DESCRIPTION:"+icsEsc(x.badge+(x.review?" · समीक्षाधीन":"")),"END:VEVENT")}if(ids.includes("nepal-sambat")){const rows=await db("ns_festival_dates?start_ad=gte."+from+"&start_ad=lte."+to+"&select=*&order=start_ad.asc") as any[],fs=await db("ns_festivals?select=*") as any[],fm=new Map(fs.map(x=>[x.id,x]));for(const r of rows){const x:any=fm.get(r.festival_id);if(x)lines.push("BEGIN:VEVENT","UID:ns-"+r.festival_id+"-"+r.start_ad+"@meropatro","DTSTART;VALUE=DATE:"+icsDate(r.start_ad),"DTEND;VALUE=DATE:"+icsDate(add(r.end_ad,1)),"SUMMARY:"+icsEsc(x.dev+" · "+x.en),"DESCRIPTION:"+icsEsc(badge(r.confidence)+(x.status==="review"?" · समीक्षाधीन":"")),"END:VEVENT")}}lines.push("END:VCALENDAR");return new Response(lines.join("\r\n")+"\r\n",{headers:{"content-type":"text/calendar; charset=utf-8","cache-control":DAYCACHE}})}

const EPOCH=1948439.5,jd=(d:string)=>Date.parse(d+"T00:00:00Z")/DAY+2440587.5,fromJd=(x:number)=>new Date((x-2440587.5)*DAY).toISOString().slice(0,10);
function toJd(y:number,m:number,d:number){return d+Math.ceil(29.5*(m-1))+(y-1)*354+Math.floor((3+11*y)/30)+EPOCH-1} function tab(d:string){const x=Math.floor(jd(d))+0.5,y=Math.floor((30*(x-EPOCH)+10646)/10631),m=Math.min(12,Math.ceil((x-(29+toJd(y,1,1)))/29.5)+1);return{year:y,month:m,day:x-toJd(y,m,1)+1}} function fromTab(y:number,m:number,d:number){return fromJd(toJd(y,m,d))}
function mid(d:string){return new Date(Date.parse(d+"T00:00:00Z")-345*60000)} function rs(d:string,lat:number,lon:number){const o=new Astronomy.Observer(lat,lon,0),s=mid(d),rise=Astronomy.SearchRiseSet(Astronomy.Body.Sun,o,+1,s,1)?.date,set=Astronomy.SearchRiseSet(Astronomy.Body.Sun,o,-1,s,1)?.date;if(!rise||!set)throw new Error("sunrise_sunset_unavailable");return{rise,set}}
function ld(d:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)} function cres(d:string,lat:number,lon:number){const {set}=rs(d,lat,lon),t=new Date(set.getTime()+600000),nm=Astronomy.SearchMoonPhase(0,new Date(t.getTime()-3*DAY),3),age=nm?(t.getTime()-nm.date.getTime())/3600000:-1,o=new Astronomy.Observer(lat,lon,0),eq=Astronomy.Equator(Astronomy.Body.Moon,t,o,true,true),hor=Astronomy.Horizon(t,o,eq.ra,eq.dec,"normal"),elong=Astronomy.AngleFromSun(Astronomy.Body.Moon,t);return{visible:age>=18&&hor.altitude>=5&&elong>=10,ageHours:age,altitude:hor.altitude,elongation:elong}}
function ms(hy:number,hm:number,lat:number,lon:number){const a=fromTab(hy,hm,1),nm=Astronomy.SearchMoonPhase(0,new Date(Date.parse(a+"T00:00:00Z")-5*DAY),10);if(!nm)return a;let d=ld(nm.date);for(let i=0;i<3;i++){if(cres(d,lat,lon).visible)return add(d,1);d=add(d,1)}return d}
function hof(d:string,lat:number,lon:number){const t=tab(d);for(const [y,m] of [[t.year,t.month],t.month===12?[t.year+1,1]:[t.year,t.month+1],t.month===1?[t.year-1,12]:[t.year,t.month-1]] as [number,number][]){const s=ms(y,m,lat,lon),diff=Math.round((Date.parse(d)-Date.parse(s))/DAY);if(diff>=0&&diff<30){const next=ms(m===12?y+1:y,m===12?1:m+1,lat,lon);if(d<next)return{year:y,month:m,day:diff+1,basis:"expected"}}}return{...t,basis:"expected"}}
const HM=[["مُحَرَّم","मुहर्रम","Muharram"],["صَفَر","सफर","Safar"],["رَبِيع ٱلْأَوَّل","रबी-उल-अव्वल","Rabi al-Awwal"],["رَبِيع ٱلثَّانِي","रबी-उस-सानी","Rabi al-Thani"],["جُمَادَىٰ ٱلْأُولَىٰ","जमादी-उल-अव्वल","Jumada al-Ula"],["جُمَادَىٰ ٱلثَّانِيَة","जमादी-उस-सानी","Jumada al-Thaniya"],["رَجَب","रजब","Rajab"],["شَعْبَان","शाबान","Sha'ban"],["رَمَضَان","रमजान","Ramadan"],["شَوَّال","शव्वाल","Shawwal"],["ذُو ٱلْقَعْدَة","जिल्काद","Dhu al-Qa'dah"],["ذُو ٱلْحِجَّة","जिलहिज्जा","Dhu al-Hijjah"]];
const METHODS={karachi:{label:"University of Islamic Sciences, Karachi",fajr:18,isha:18},mwl:{label:"Muslim World League",fajr:18,isha:17},isna:{label:"ISNA",fajr:15,isha:15}} as const; type Method=keyof typeof METHODS;
function prayers(d:string,lat:number,lon:number,m:Method,asr:"hanafi"|"shafii"){const o=new Astronomy.Observer(lat,lon,0),start=mid(d),{rise,set}=rs(d,lat,lon),noon=Astronomy.SearchHourAngle(Astronomy.Body.Sun,o,0,start).time.date,dec=Astronomy.Equator(Astronomy.Body.Sun,noon,o,true,true).dec,k=asr==="hanafi"?2:1,aa=Math.atan(1/(k+Math.tan(Math.abs(lat-dec)*Math.PI/180)))*180/Math.PI,need=(x:any)=>{if(!x)throw new Error("prayer_time_unavailable");return x.date};return{fajr:need(Astronomy.SearchAltitude(Astronomy.Body.Sun,o,+1,start,1,-METHODS[m].fajr)),sunrise:rise,dhuhr:new Date(noon.getTime()+120000),asr:need(Astronomy.SearchAltitude(Astronomy.Body.Sun,o,-1,noon,1,aa)),maghrib:set,isha:need(Astronomy.SearchAltitude(Astronomy.Body.Sun,o,-1,set,1,-METHODS[m].isha))}}
function qb(lat:number,lon:number){const r=Math.PI/180,d=(39.826206-lon)*r,y=Math.sin(d),x=Math.cos(lat*r)*Math.tan(21.422487*r)-Math.sin(lat*r)*Math.cos(d);return((Math.atan2(y,x)/r)+360)%360}
const HQ=z.object({date:z.string().regex(DATE).optional(),lat:z.coerce.number().min(-60).max(60).default(27.7172),lon:z.coerce.number().min(-180).max(180).default(85.324),method:z.enum(["karachi","mwl","isna"]).default("karachi"),asr:z.enum(["hanafi","shafii"]).default("hanafi")}).strict();
export async function hijri(sp:URLSearchParams){const q=HQ.safeParse(Object.fromEntries(sp));if(!q.success)return bad("invalid_query",q.error.flatten());const d=q.data.date||today();if(!valid(d))return bad("invalid_date");const h=hof(d,q.data.lat,q.data.lon),p=prayers(d,q.data.lat,q.data.lon,q.data.method,q.data.asr),t=(x:Date)=>x.toLocaleTimeString("en-GB",{timeZone:"Asia/Kathmandu",hour:"2-digit",minute:"2-digit"}),cv=cres(d,q.data.lat,q.data.lon),mn=HM[h.month-1];return j({ok:true,date:d,hijri:{...h,month_name:{ar:mn[0],dev:mn[1],en:mn[2]}},prayer:{fajr:t(p.fajr),sunrise:t(p.sunrise),dhuhr:t(p.dhuhr),asr:t(p.asr),maghrib:t(p.maghrib),isha:t(p.isha)},method:METHODS[q.data.method].label,asrSchool:q.data.asr,qibla:Math.round(qb(q.data.lat,q.data.lon)*10)/10,crescent:{visible:cv.visible,ageHours:+cv.ageHours.toFixed(1),altitude:+cv.altitude.toFixed(1),elongation:+cv.elongation.toFixed(1)},badge:"सम्भावित",note:"Hijri month starts are astronomical expectations until Nepal's official moon-sighting announcement."},200,{"cache-control":CACHE})}
const CITIES=[["काठमाडौं",27.7172,85.324],["बीरगञ्ज",27.0104,84.8779],["नेपालगञ्ज",28.05,81.6167],["जनकपुर",26.7288,85.9263],["कृष्णनगर",27.5667,83.0333],["विराटनगर",26.4525,87.2718],["भैरहवा",27.5059,83.4495],["राजविराज",26.5395,86.7475],["गौर",26.7667,85.2833],["पोखरा",28.2096,83.9856]] as const;
const RQ=z.object({hy:z.coerce.number().int().min(1300).max(1700),city:z.coerce.number().int().min(0).max(9).default(0),method:z.enum(["karachi","mwl","isna"]).default("karachi")}).strict();
export async function ramadan(sp:URLSearchParams){const q=RQ.safeParse(Object.fromEntries(sp));if(!q.success)return bad("invalid_query",q.error.flatten());const c=CITIES[q.data.city],start=ms(q.data.hy,9,c[1],c[2]),end=ms(q.data.hy,10,c[1],c[2]),days:any[]=[],t=(x:Date)=>x.toLocaleTimeString("en-GB",{timeZone:"Asia/Kathmandu",hour:"2-digit",minute:"2-digit"});for(let d=start,i=1;d<end;d=add(d,1),i++){const p=prayers(d,c[1],c[2],q.data.method,"hanafi");days.push({roza:i,date:d,sehriEnds:t(p.fajr),iftar:t(p.maghrib)})}return j({ok:true,hijriYear:q.data.hy,city:c[0],expectedStart:start,expectedEid:end,badge:"सम्भावित",days},200,{"cache-control":DAYCACHE})}

export async function nepalSambat(sp:URLSearchParams){const ad=sp.get("ad")||today();if(!valid(ad))return bad("invalid_ad");const [archive,days]=await Promise.all([db("astronomy_calendar_map?ad_date=eq."+ad+"&select=payload&limit=1"),db("ns_days?ad=eq."+ad+"&select=*&limit=1")]) as [any[],any[]],payload=archive[0]?.payload,n=payload?.ns,base=days[0];if(!n&&!base)return j({ok:false,error:"date_outside_coverage"},422,{"cache-control":"no-store"});const year=n?.year||base.ns_year,until=add(ad,60),[dates,fs]=await Promise.all([db("ns_festival_dates?start_ad=gte."+ad+"&start_ad=lte."+until+"&select=*&order=start_ad.asc&limit=12"),db("ns_festivals?select=*")]) as [any[],any[]],fm=new Map(fs.map(x=>[x.id,x])),upcoming=dates.map(r=>{const f:any=fm.get(r.festival_id);return{id:r.festival_id,dev:f?.dev,roman:f?.roman,en:f?.en,start:r.start_ad,end:r.end_ad,confidence:r.confidence,badge:badge(r.confidence),declaredAnnually:!!f?.declared_annually,status:f?.status,review:f?.status==="review",review_label:f?.status==="review"?"समीक्षाधीन":null}}),ny=await db("ns_festival_dates?ns_year=eq."+(Number(year)+1)+"&festival_id=eq.mha-puja&select=start_ad&limit=1") as any[],next=ny[0]?.start_ad||null;return j({ok:true,ad,lunar:n||{year:base.ns_year,month_no:base.ns_month,paksha:base.ns_paksha,tithi_number:base.ns_tithi,adhika:base.ns_adhik,formatted:base.ns_label,formatted_newa:base.ns_label_newa},solar:base?{year:base.solar_year,month:base.solar_month,day:base.solar_day}:null,nextNewYear:next?{nsYear:Number(year)+1,ad:next,days:Math.round((Date.parse(next)-Date.parse(ad))/DAY)}:null,upcoming,source:"Patro astronomical archive is primary; engine-generated NS tables provide solar mapping and festival index"},200,{"cache-control":CACHE})}
export async function nsFestivals(sp:URLSearchParams){const year=Number(sp.get("year"));if(!Number.isInteger(year)||year<1000||year>1300)return bad("invalid_ns_year");const [rows,fs]=await Promise.all([db("ns_festival_dates?ns_year=eq."+year+"&select=*&order=start_ad.asc"),db("ns_festivals?select=*")]) as [any[],any[]],fm=new Map(fs.map(x=>[x.id,x])),festivals=rows.map(r=>{const f:any=fm.get(r.festival_id);return{id:r.festival_id,dev:f?.dev,newa:f?.dev?devanagariToNewa(f.dev):null,roman:f?.roman,en:f?.en,start:r.start_ad,end:r.end_ad,tradition:f?.tradition,places:f?.places||[],publicHoliday:f?.public_holiday||"none",confidence:r.confidence,badge:badge(r.confidence),declaredAnnually:!!f?.declared_annually,status:f?.status,review:f?.status==="review",review_label:f?.status==="review"?"समीक्षाधीन":null}});return j({ok:true,year,festivals,review:festivals.filter((x:any)=>x.review).map((x:any)=>({id:x.id,dev:x.dev}))},200,{"cache-control":DAYCACHE})}
export async function nsConvert(sp:URLSearchParams){let ad=sp.get("ad");try{if(!ad&&sp.get("ns")){const m=sp.get("ns")!.match(/^(\d{3,4})-(\d{1,2})-(thwa|ga)-(\d{1,2})$/);if(!m)return bad("invalid_ns_format");const rows=await db("ns_days?ns_year=eq."+m[1]+"&ns_month=eq."+m[2]+"&ns_paksha=eq."+m[3]+"&ns_tithi=eq."+m[4]+"&ns_adhik=eq."+(sp.get("adhik")==="1")+"&select=*&order=ad.asc&limit=1") as any[];ad=rows[0]?.ad}if(!ad&&sp.get("solar")){const m=sp.get("solar")!.match(/^(\d{3,4})-(\d{1,2})-(\d{1,2})$/);if(!m)return bad("invalid_solar_format");const rows=await db("ns_days?solar_year=eq."+m[1]+"&solar_month=eq."+m[2]+"&solar_day=eq."+m[3]+"&select=*&limit=1") as any[];ad=rows[0]?.ad}if(!ad||!valid(ad))return bad("give_ad_ns_or_solar");return await nepalSambat(new URLSearchParams({ad}))}catch(err){return j({ok:false,error:String((err as Error).message||err)},422,{"cache-control":"no-store"})}}
export async function nsIcs(sp:URLSearchParams){const year=Number(sp.get("year"));if(!Number.isInteger(year)||year<1000||year>1300)return bad("invalid_ns_year");const r=await nsFestivals(new URLSearchParams({year:String(year)}));if(r.status!==200)return r;const p=await r.json(),lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Mero Patro//Nepal Sambat//NE","CALSCALE:GREGORIAN","X-WR-CALNAME:नेपाल संवत् "+year,"REFRESH-INTERVAL;VALUE=DURATION:P7D"];for(const x of p.festivals)lines.push("BEGIN:VEVENT","UID:ns-"+x.id+"-"+x.start+"@meropatro","DTSTART;VALUE=DATE:"+icsDate(x.start),"DTEND;VALUE=DATE:"+icsDate(add(x.end,1)),"SUMMARY:"+icsEsc(x.dev+" · "+x.en),"DESCRIPTION:"+icsEsc(x.badge+(x.review?" · समीक्षाधीन":"")),"END:VEVENT");lines.push("END:VCALENDAR");return new Response(lines.join("\r\n")+"\r\n",{headers:{"content-type":"text/calendar; charset=utf-8","cache-control":DAYCACHE}})}
const SQ=z.object({to:z.enum(["tirhuta","limbu","newa"]),text:z.string().max(2000)}).strict(); export function scripts(sp:URLSearchParams){const q=SQ.safeParse({to:sp.get("to"),text:sp.get("text")||""});if(!q.success)return bad("invalid_query",q.error.flatten());const f=q.data.to==="tirhuta"?devanagariToTirhuta:q.data.to==="limbu"?devanagariToLimbu:devanagariToNewa;return j({ok:true,to:q.data.to,text:q.data.text,result:f(q.data.text)},200,{"cache-control":DAYCACHE})}

const AN:any={tamang:[["मुसा","Rat","🐀"],["गाई","Cow","🐄"],["बाघ","Tiger","🐅"],["खरायो","Rabbit","🐇"],["ड्रागन (बादल)","Dragon (Cloud)","🐉"],["सर्प","Snake","🐍"],["घोडा","Horse","🐎"],["भेडा","Sheep","🐑"],["बाँदर","Monkey","🐒"],["चरा","Bird","🐦"],["कुकुर","Dog","🐕"],["सुँगुर","Pig","🐖"]],tibetan:[["मुसा","Rat","🐀"],["गोरु","Ox","🐂"],["बाघ","Tiger","🐅"],["खरायो","Rabbit","🐇"],["ड्रागन","Dragon","🐉"],["सर्प","Snake","🐍"],["घोडा","Horse","🐎"],["भेडा","Sheep","🐑"],["बाँदर","Monkey","🐒"],["चरा","Bird","🐓"],["कुकुर","Dog","🐕"],["सुँगुर","Pig","🐖"]],gurung:[["मुसा","Mouse","🐁"],["गाई","Cow","🐄"],["बाघ","Tiger","🐅"],["बिरालो","Cat","🐈"],["गरुड","Eagle","🦅"],["सर्प","Serpent","🐍"],["घोडा","Horse","🐎"],["भेडा","Sheep","🐑"],["बाँदर","Monkey","🐒"],["चरा","Bird","🐦"],["कुकुर","Dog","🐕"],["मृग","Deer","🦌"]]};
function animal(c:string,y:number){const i=((y-2020)%12+12)%12,[dev,en,emoji]=AN[c][i];return{index:i,dev,en,emoji}} function element(y:number){const E:any=[["काठ","Wood","ཤིང"],["आगो","Fire","མེ"],["माटो","Earth","ས"],["धातु","Metal","ལྕགས"],["पानी","Water","ཆུ"]],s=((y-4)%10+10)%10,[dev,en,bo]=E[Math.floor(s/2)];return{dev,en,bo,gender:s%2===0?"male":"female",genderDev:s%2===0?"पुरुष":"स्त्री"}}
export async function lho(sp:URLSearchParams){const d=sp.get("date")||today();if(!valid(d))return bad("invalid_date");const y=Number(d.slice(0,4)),rows=await db("community_dates?suite=eq.lhosar&festival_id=in.(sonam-lhosar,tamu-lhosar,gyalpo-lhosar)&year=in.("+(y-1)+","+y+","+(y+1)+")&region=is.null&select=*") as D[],find=(id:string,yr:number)=>rows.find(r=>r.festival_id===id&&r.year===yr)?.main,sonam=find("sonam-lhosar",y)||y+"-02-01",gyalpo=find("gyalpo-lhosar",y)||y+"-02-15",tamu=find("tamu-lhosar",y)||y+"-12-30",ty=d>=sonam?y:y-1,tib=d>=gyalpo?y:y-1,gy=d>=tamu?y+1:y;return j({ok:true,date:d,tamang:{...animal("tamang",ty),era:ty+836,cycleYear:ty},tibetan:{...animal("tibetan",tib),element:element(tib),era:tib+127,cycleYear:tib},gurung:{...animal("gurung",gy),cycleYear:gy},boundaries:{sonam,gyalpo,tamu},source:"engine-generated Lhosar dates + arithmetic cycles"},200,{"cache-control":DAYCACHE})}

async function user(req:Request){const a=req.headers.get("authorization")||"";if(!a.startsWith("Bearer "))return null;const r=await fetch(SUPABASE_URL+"/auth/v1/user",{headers:{apikey:SERVICE_KEY,authorization:a},signal:AbortSignal.timeout(5000)});if(!r.ok)return null;return await r.json() as any}
export async function getPreferences(req:Request){const u=await user(req);if(!u)return j({ok:false,error:"authentication_required"},401,{"cache-control":"no-store"});const rows=await db("user_community_preferences?user_id=eq."+u.id+"&select=communities&limit=1") as any[];return j({ok:true,communities:rows[0]?.communities||[]},200,{"cache-control":"private, no-store"})}
const PB=z.object({communities:z.array(z.enum(COMMUNITY_IDS)).max(6)}).strict(); export async function putPreferences(req:Request){const u=await user(req);if(!u)return j({ok:false,error:"authentication_required"},401,{"cache-control":"no-store"});let b;try{b=await req.json()}catch{return bad("invalid_json")}const q=PB.safeParse(b);if(!q.success)return bad("invalid_request",q.error.flatten());await db("user_community_preferences?on_conflict=user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:u.id,communities:[...new Set(q.data.communities)],updated_at:new Date().toISOString()})});return j({ok:true,communities:q.data.communities},200,{"cache-control":"private, no-store"})}
async function admin(req:Request){const u=await user(req);return u?.app_metadata?.role==="admin"?u:null}
const OB=z.object({suite:z.enum(SUITES),festival_id:z.string().min(1).max(120),year:z.number().int().min(2020).max(2050),start_ad:z.string().regex(DATE),end_ad:z.string().regex(DATE).optional(),note:z.string().max(500).optional()}).strict();
export async function adminCommunityOverride(req:Request){const u=await admin(req);if(!u)return j({ok:false,error:"admin_required"},403,{"cache-control":"no-store"});let b;try{b=await req.json()}catch{return bad("invalid_json")}const q=OB.safeParse(b);if(!q.success)return bad("invalid_request",q.error.flatten());await db("community_overrides?on_conflict=suite,festival_id,year",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({...q.data,created_by:u.email||u.id})});return j({ok:true,badge:"घोषित",override:q.data},200,{"cache-control":"no-store"})}
const NB=z.object({ns_year:z.number().int().min(1000).max(1300),festival_id:z.string().min(1).max(120),start_ad:z.string().regex(DATE),end_ad:z.string().regex(DATE),note:z.string().max(500).optional()}).strict();
export async function adminNsFestival(req:Request){const u=await admin(req);if(!u)return j({ok:false,error:"admin_required"},403,{"cache-control":"no-store"});let b;try{b=await req.json()}catch{return bad("invalid_json")}const q=NB.safeParse(b);if(!q.success)return bad("invalid_request",q.error.flatten());await db("ns_festival_dates?on_conflict=ns_year,festival_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({...q.data,confidence:"confirmed",confirmed_by:u.email||u.id})});return j({ok:true,badge:"घोषित",festival:q.data},200,{"cache-control":"no-store"})}
