const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
const CSS=`
.mp-global-header{position:sticky;top:0;z-index:2147483000;background:rgba(255,255,255,.96);border-bottom:1px solid #e5e7eb;backdrop-filter:blur(14px);font-family:Inter,"Noto Sans Devanagari",system-ui,sans-serif}
.mp-global-inner{width:min(1200px,calc(100% - 28px));height:64px;margin:auto;display:flex;align-items:center;gap:22px}.mp-global-brand{color:#176f3b!important;text-decoration:none!important;font-weight:900!important;font-size:20px}.mp-global-nav{display:flex;align-self:stretch;align-items:stretch;gap:2px}.mp-global-nav a{display:flex;align-items:center;padding:0 10px;color:#4b5563!important;text-decoration:none!important;font-weight:700!important;font-size:14px;border-bottom:2px solid transparent}.mp-global-nav a:hover,.mp-global-nav a[aria-current=page]{color:#176f3b!important;background:#eef6f1;border-bottom-color:#176f3b}.mp-global-spacer{flex:1}.mp-global-tools{color:#176f3b!important;text-decoration:none!important;font-weight:800!important}.mp-global-footer{margin-top:56px;padding:38px max(16px,calc((100% - 1200px)/2)) 90px;border-top:1px solid #e5e7eb;background:#fff;font-family:Inter,"Noto Sans Devanagari",system-ui,sans-serif}.mp-global-footer__grid{display:grid;grid-template-columns:1.3fr repeat(3,1fr);gap:28px}.mp-global-footer strong{font-size:18px}.mp-global-footer p{color:#4b5563;max-width:320px}.mp-global-footer h2{font-size:14px;margin:0 0 8px}.mp-global-footer a{display:block;color:#4b5563!important;text-decoration:none!important;padding:3px 0}.mp-global-footer a:hover{color:#176f3b!important}.mp-global-bottom{display:none}.mp-tab-bridge{display:none!important}body>header.top{display:none!important}body>main>.footer{display:none!important}
@media(max-width:820px){.mp-global-nav{display:none}.mp-global-footer__grid{grid-template-columns:1fr 1fr}.mp-global-footer__brand{grid-column:1/-1}}
@media(max-width:640px){body{padding-bottom:66px}.mp-global-inner{height:56px}.mp-global-footer__grid{grid-template-columns:1fr}.mp-global-footer__brand{grid-column:auto}.mp-global-footer{padding-bottom:90px}.mp-global-bottom{position:fixed;left:0;right:0;bottom:0;z-index:2147483000;display:grid;grid-template-columns:repeat(5,1fr);background:rgba(255,255,255,.97);border-top:1px solid #e5e7eb;padding:5px 3px calc(5px + env(safe-area-inset-bottom));backdrop-filter:blur(14px)}.mp-global-bottom a{min-height:50px;display:grid;place-items:center;gap:1px;color:#4b5563!important;text-decoration:none!important;font:700 10px Inter,system-ui}.mp-global-bottom b{font-size:18px;font-weight:500}}
`;
function current(path:string,target:string){return path===target||path.startsWith(target+"/")?' aria-current="page"':''}
export function sharedHeader(path:string){
 return '<header class="mp-global-header" data-mp-shared-shell="1"><div class="mp-global-inner"><a class="mp-global-brand" href="/">MeroPatro</a><nav class="mp-global-nav" aria-label="मुख्य नेभिगेसन"><a href="/"'+current(path,"/")+'>पात्रो</a><a href="/rashifal/aries/aaja"'+current(path,"/rashifal")+'>राशिफल</a><a href="/convert"'+current(path,"/convert")+'>मिति रूपान्तरण</a><a href="/tv"'+current(path,"/tv")+'>लाइभ टिभी</a><a href="/my-diary"'+current(path,"/my-diary")+'>मेरो डायरी</a></nav><span class="mp-global-spacer"></span><a class="mp-global-tools" href="/tools">Tools</a></div><div class="mp-tab-bridge" aria-hidden="true"><button data-tab="calendar"></button><button data-tab="tools"></button><button data-tab="astrology"></button><button data-tab="otd"></button><button data-tab="tv"></button></div></header>';
}
export function sharedFooter(){
 return '<footer class="mp-global-footer"><div class="mp-global-footer__grid"><section class="mp-global-footer__brand"><strong>MeroPatro</strong><p>नेपाली पात्रो, तिथि, चाडपर्व, राशिफल र दैनिक उपयोगी सुविधा।</p></section><section><h2>पात्रो</h2><a href="/">आजको पात्रो</a><a href="/rashifal/aries/aaja">राशिफल</a><a href="/convert">मिति रूपान्तरण</a></section><section><h2>सुविधाहरू</h2><a href="/tv">लाइभ टिभी</a><a href="/fm">रेडियो</a><a href="/tools">Tools</a></section><section><h2>जानकारी</h2><a href="/about">हाम्रो बारेमा</a><a href="/sources">स्रोत र शुद्धता</a><a href="/privacy">गोपनीयता</a><a href="/terms">सर्तहरू</a><a href="/contact">सम्पर्क</a></section></div></footer>';
}
export function sharedBottomNav(){
 return '<nav class="mp-global-bottom" aria-label="मोबाइल नेभिगेसन"><a href="/"><b>▣</b><span>पात्रो</span></a><a href="/tv"><b>▻</b><span>टिभी</span></a><a href="/convert"><b>⇄</b><span>रूपान्तरण</span></a><a href="/my-diary"><b>✓</b><span>डायरी</span></a><a href="/tools"><b>•••</b><span>थप</span></a></nav>';
}
export function sharedChrome(html:string,path:string){
 if(!html||html.includes('data-mp-shared-shell="1"'))return html;
 let out=html.replace(/<html(?![^>]*\blang=)([^>]*)>/i,'<html lang="ne"$1>');
 out=out.replace('</head>','<style id="mp-shared-css">'+CSS+'</style></head>');
 out=out.replace(/<body([^>]*)>/i,match=>match+sharedHeader(path));
 out=out.replace('</body>',sharedFooter()+sharedBottomNav()+'</body>');
 return out;
}
