import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';const read=p=>readFileSync(p,'utf8');
test('persistent player defers HLS and preserves native playback and controls',()=>{const s=read('src/media/MediaProvider.tsx');assert.match(s,/import type Hls from "hls.js"/);assert.match(s,/import\("hls.js"\)/);assert.ok(s.includes('audio.canPlayType("application/vnd.apple.mpegurl")'));assert.ok(s.includes('hlsMedia && !nativeHls ? await loadHls() : null'));assert.ok(s.includes('epoch !== playEpoch.current'));for(const control of ['setSleepMinutes','setMuted','setVolume','mediaSession','AudioContext','patro:media-status'])assert.ok(s.includes(control));assert.ok(read('src/main.tsx').includes('MediaProvider'));});
test('sky card waits for idle or intersection and preserves original content source',()=>{const s=read('src/components/DeferredHomeSkyFact.tsx');assert.ok(s.includes('IntersectionObserver'));assert.ok(s.includes('requestIdleCallback'));assert.ok(s.includes('minHeight:240'));assert.ok(s.includes('import("./HomeSkyFact")'));assert.ok(read('src/components/HomeSkyFact.tsx').includes('buildFacts(now, language)'));assert.ok(read('src/HomePageCurrent.tsx').includes('DeferredHomeSkyFact'));assert.ok(read('src/components/HomePanchang.tsx').includes('Supplemental calculations wait until idle'));assert.ok(read('src/components/HomePanchang.tsx').includes('return () => { active = false; window.clearTimeout(timer)')); });
test('installation and standalone launch automatically cache build feature assets with retries',()=>{const pwa=read('src/pwa.ts'),sw=read('public/sw.js'),vite=read('vite.config.ts');assert.ok(vite.includes('pwa-optional-assets.json'));for(const event of ['appinstalled','online','display-mode: standalone','WARM_FEATURE_ASSETS'])assert.ok(pwa.includes(event));assert.ok(sw.includes('optional_assets_incomplete_'));assert.ok(sw.includes('if (await shell.match(request)) return'));assert.ok(sw.includes('FEATURE_ASSETS_RETRY'));assert.ok(sw.includes('manifest.assets.length > 300'));assert.ok(sw.includes('isPrivatePath'));assert.ok(sw.includes('isSafeCalendarRequest'));});
test('service worker caches installed HLS/astronomy assets and retries an interrupted download',async()=>{const{runInNewContext}=await import('node:vm');const handlers={},stored=new Map(),messages=[],calls=[];let interrupt=true;const origin='https://aafnaipatro.com';class LocalRequest extends Request{constructor(url,options){super(new URL(typeof url==='string'?url:url.url,origin),options)}}const context={self:{location:{origin},addEventListener:(type,callback)=>handlers[type]=callback},caches:{open:async()=>({match:async request=>stored.get(request.url),put:async(request,response)=>stored.set(request.url,response)})},Request:LocalRequest,Response,URL,Date,console,fetch:async input=>{const path=typeof input==='string'?input:new URL(input.url).pathname;calls.push(path);if(path==='/pwa-optional-assets.json')return Response.json({assets:['/assets/media-player-one.js','/assets/astronomy-one.js','/api/private-export']});if(path.includes('astronomy')&&interrupt)return new Response('',{status:503});return new Response('export const available=true',{headers:{'content-type':'text/javascript','cache-control':'public,max-age=31536000'}})}};runInNewContext(read('public/sw.js'),context);async function warm(){let pending;handlers.message({data:{type:'WARM_FEATURE_ASSETS'},source:{postMessage:message=>messages.push(message)},waitUntil:promise=>pending=promise});await pending}await warm();assert.equal(messages.at(-1).type,'FEATURE_ASSETS_RETRY');assert(stored.has(origin+'/assets/media-player-one.js'));interrupt=false;await warm();assert.equal(messages.at(-1).type,'FEATURE_ASSETS_READY');assert(stored.has(origin+'/assets/astronomy-one.js'));assert.equal(calls.filter(path=>path==='/assets/media-player-one.js').length,1);assert(!calls.includes('/api/private-export'));});

test('homepage note and voice typing remain complete but load after first paint',()=>{
 const home=read('src/HomePageCurrent.tsx');
 const deferred=read('src/components/DeferredHomeQuickNote.tsx');
 const full=read('src/components/HomeQuickNote.tsx');
 assert.ok(home.includes('DeferredHomeQuickNote'));
 assert.ok(!home.includes('import { HomeQuickNote }'));
 for(const guard of ['IntersectionObserver','requestIdleCallback','minHeight: 240','import("./HomeQuickNote")'])assert.ok(deferred.includes(guard),`missing lazy note guard ${guard}`);
 for(const feature of ['useNepaliDictation','InlineDictationPreview','syncLifeTools','<VoiceHelp','<GoogleAuthButton','className="qn-save"'])assert.ok(full.includes(feature),`lost existing notes feature ${feature}`);
});
