import {useMemo,useState} from 'react';
import type {BirthModel} from './birth-panchang';
import {NAKSHATRAS} from '../patro-tools/core/names';
import {reviewedStar,STAR_TRADITIONS} from './traditions';
import {communityCalendars,orderCalendars} from './community-calendars';
import {birthSky} from './sky';
import {MoonSvg} from '../patro-tools/birth-card/MoonSvg';
import {StandUnderThisSky} from '../components/StandUnderThisSky';
export default function BirthdayCulture({model,language}:{model:BirthModel;language:'ne'|'en'}){
 const [open,setOpen]=useState(false),calendars=useMemo(()=>orderCalendars(communityCalendars(model),model.profile.mode),[model]),sky=useMemo(()=>birthSky(model),[model]);const star=reviewedStar(model.p.nakshatra),source=STAR_TRADITIONS[model.p.nakshatra];
 const full=model.profile.mode==='full',tx=(ne:string,en:string)=>language==='ne'?ne:en;
 return <><section className="patro-tool-card"><h2>{tx('नेपालका पात्रोमा मेरो जन्मदिन','My birthday in Nepal’s calendars')}</h2><dl>{calendars.map(c=><div key={c.id}><dt><strong>{c.label}</strong></dt><dd style={{margin:0,overflowWrap:'anywhere'}}>{c.value}</dd></div>)}</dl><p>{tx('समुदायका आफ्नै converters र मान्यता; परम्परा फरक हुन सक्छ।','Uses each existing community converter and convention; traditions may differ.')}</p></section>
 {full?<section className="patro-tool-card"><h2>{tx('जन्म नक्षत्र','Birth star')} · {NAKSHATRAS[model.p.nakshatra]}</h2><p>नामाक्षर / Name syllable: {model.syllable}</p>{star?<><p>{star.deity} · {star.symbol} · जन्म-वृक्ष / Tree: {star.tree}</p>{star.nepalAlternative?<p>Local alternative: {star.nepalAlternative.species} ({star.nepalAlternative.region})</p>:<p>{tx('रोप्नुअघि स्थानीय नर्सरीसँग उपयुक्त प्रजाति र ठाउँ पक्का गर्नुहोस्।','Confirm a suitable native species and site with a local nursery before planting.')}</p>}</>:<p>{tx('देवता र वृक्ष तालिका नामसहित योग्य समीक्षकको स्वीकृतिपछि देखाइनेछ।','Deity and tree details await a named qualified reviewer. Regional planting alternatives require ecological review.')}</p>}<a href={source?.source}>Nakshatravana source</a> · <a href={source?.starSource}>Star tradition source</a><p>{tx('परम्परा फरक हुन सक्छ; आत्मचिन्तन, भविष्यवाणी होइन।','Traditions may differ; a reflection, not a prediction.')}</p></section>:null}
 <section className="patro-tool-card"><h2>{tx('जन्मको आकाश','Sky at birth')}</h2><MoonSvg angle={model.p.moonPhaseAngle}/><p>{model.instant.toISOString()} · {model.place.name}</p><table><caption>{tx('क्षितिजमाथि हुनु देख्न सकिने ग्यारेन्टी होइन; बादल र सूर्यको उज्यालोले असर गर्छ।','Above the horizon does not guarantee visibility; daylight and clouds matter.')}</caption><thead><tr><th>Body</th><th>Altitude</th><th>Azimuth</th><th>Horizon</th></tr></thead><tbody>{sky.map(p=><tr key={p.body}><th>{p.body}</th><td>{p.altitude.toFixed(1)}°</td><td>{p.azimuth.toFixed(1)}°</td><td>{p.aboveHorizon?'Above / माथि':'Below / तल'}</td></tr>)}</tbody></table><button type="button" onClick={()=>setOpen(true)}>{tx('आकाश अनुभूति खोल्नुहोस्','Stand under this sky')}</button><p>{tx('अनुभूति दृश्यका तारा सजावटी हुन्; माथिको planet table गणना गरिएको हो।','The immersive star background is decorative; the planet table above is computed.')}</p><StandUnderThisSky open={open} onClose={()=>setOpen(false)} selectedDate={model.profile.date} sync={null} tithi={null} cosmic={null} apod={null}/></section></>;
}
