import { useState } from 'react';
import {readBirthday,saveBirthday,BIRTHDAY_KEY,type BirthdayProfile} from './storage';
import {threeBirthdays,daysUntil,type BirthdayYear} from './three-birthdays';
import {bsAdapter} from '../patro-tools-integration/bsAdapter';
import {readPlace} from '../place/place';
export default function BirthdayPage() {
 const [profile,setProfile]=useState<BirthdayProfile>(()=>readBirthday()||{name:'',date:'2000-01-01',mode:'full'}),[system,setSystem]=useState('ad'),[bs,setBs]=useState('2056-09-17'),[rows,setRows]=useState<BirthdayYear[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[language,setLanguage]=useState<'ne'|'en'>('ne');
 const today=new Date().toLocaleDateString('en-CA',{timeZone:profile.place?.tz||'Asia/Kathmandu'}),tx=(ne:string,en:string)=>language==='ne'?ne:en;
 async function build(){setBusy(true);setRows([]);try{let date=profile.date;if(system==='bs'){const[y,m,d]=bs.replace(/[०-९]/g,c=>String('०१२३४५६७८९'.indexOf(c))).split('-').map(Number),ad=bsAdapter.toAD({year:y,month:m,day:d});date=`${ad.year}-${String(ad.month).padStart(2,'0')}-${String(ad.day).padStart(2,'0')}`;setProfile({...profile,date});}if(date>today)throw Error('Birth date must be today or earlier.');setRows(await threeBirthdays(date,Number(today.slice(0,4))));setStatus('Calculated locally from static archive. Missing future data stays unavailable.');}catch(e){setStatus(e instanceof Error?e.message:'Unavailable');}finally{setBusy(false);}}
 return <main className="ap-page birthday-page" style={{maxWidth:1000,margin:'auto',overflowWrap:'anywhere'}}><h1>{tx('मेरो असली जन्मदिन','My real birthday')}</h1><p>{tx('आत्मचिन्तन र सांस्कृतिक पात्रो; भविष्यवाणी होइन। सबै गणना यस उपकरणमा हुन्छ।','Reflection and cultural calendars, with all calculations on this device.')}</p><label>Language<select value={language} onChange={e=>setLanguage(e.target.value as typeof language)}><option value="ne">नेपाली</option><option value="en">English</option></select></label>
 <section className="patro-tool-card"><label>{tx('नाम (ऐच्छिक)','Name (optional)')}<input maxLength={80} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>AD / BS<select value={system} onChange={e=>setSystem(e.target.value)}><option value="ad">AD</option><option value="bs">BS</option></select></label>{system==='ad'?<label>{tx('जन्म मिति','Birth date')}<input type="date" value={profile.date} max={today} onChange={e=>setProfile({...profile,date:e.target.value})}/></label>:<label>BS YYYY-MM-DD<input value={bs} onChange={e=>setBs(e.target.value)}/></label>}
 <label>{tx('समय (ऐच्छिक)','Time (optional)')}<input type="time" value={profile.time||''} onChange={e=>setProfile({...profile,time:e.target.value||undefined})}/></label><label><input type="checkbox" checked={!!profile.place} onChange={e=>setProfile({...profile,place:e.target.checked?readPlace()||undefined:undefined})}/>{tx('सुरक्षित मेरो ठाउँ प्रयोग','Use my saved place')} · <a href="/tools/my-place">Set place</a></label>
 <label>{tx('दृश्य','Display mode')}<select value={profile.mode} onChange={e=>setProfile({...profile,mode:e.target.value as BirthdayProfile['mode']})}>{['full','buddhist','kirat','tamang','gurung','tibetan','muslim','calendar-only'].map(m=><option key={m}>{m}</option>)}</select></label>
 <button type="button" disabled={busy} onClick={()=>void build()}>{busy?'…':tx('गणना','Calculate')}</button><button type="button" onClick={()=>{try{saveBirthday(profile);setStatus('Saved on this device only.');}catch{setStatus('Could not save locally.');}}}>{tx('यस उपकरणमा सुरक्षित','Save locally')}</button><button type="button" onClick={()=>{try{localStorage.removeItem(BIRTHDAY_KEY);setStatus('Saved birthday removed.');}catch{setStatus('Storage unavailable.');}}}>{tx('स्थानीय जन्ममिति हटाउनुहोस्','Delete saved birthday')}</button><p role="status">{status}</p></section>
 {rows.length?<section className="patro-tool-card"><h2>{tx('तीन जन्मदिन','Three birthdays')}</h2><p>AD / BS / तिथि · {tx('काठमाडौं अभिलेखको आधारमा','Kathmandu archive basis')}. {tx('समय वा स्थानले जन्म-पञ्चाङ्गमा फरक पार्न सक्छ।','Time/place can change birth-instant panchang.')}</p><div style={{overflowX:'auto'}}><table><caption>10-year comparison · सङ्गम / Alignment = same or adjacent day</caption><thead><tr><th>Year</th><th>AD</th><th>BS</th><th>Tithi</th><th>Notes</th></tr></thead><tbody>{rows.map(r=><tr key={r.year}><th>{r.year}{r.alignment?' ✨ सङ्गम':''}</th>{[r.ad,r.bs,r.tithi].map((date,i)=><td key={i}>{date||'Unavailable'}{date?<small> · {new Date(date+'T00:00Z').toLocaleDateString(language==='ne'?'ne-NP':'en-GB',{weekday:'long',timeZone:'UTC'})} · {daysUntil(date,today)} days</small>:null}</td>)}<td>{r.note}</td></tr>)}</tbody></table></div></section>:null}
 <a href="/tools/janmadin-akhbar">{tx('पुरानै जन्मदिन अखबार','Existing birthday newspaper')}</a></main>;
}
