import {validProfile,type BirthdayProfile} from './storage';import type {Sealed} from '../patro-tools/letters/crypto';
export const FAMILY_KEY='patro.birthday.family.v1',REFLECTION_KEY='patro.birthday.reflections.v1';
export type FamilyMember=BirthdayProfile&{id:string};export type Reflection={id:string;openAt:string;sealed:Sealed;createdAt:string};
export function readFamily():FamilyMember[]{try{const rows=JSON.parse(localStorage.getItem(FAMILY_KEY)||'[]');return Array.isArray(rows)?rows.filter(r=>validProfile(r)&&typeof (r as FamilyMember).id==='string').slice(0,30):[];}catch{return[];}}
export function saveFamily(rows:FamilyMember[]){if(rows.length>30||rows.some(r=>!validProfile(r)||!r.id))throw Error('Invalid family');localStorage.setItem(FAMILY_KEY,JSON.stringify(rows));}
export function readReflections():Reflection[]{try{const rows=JSON.parse(localStorage.getItem(REFLECTION_KEY)||'[]');return Array.isArray(rows)?rows.filter(r=>typeof r.id==='string'&&Number.isFinite(Date.parse(r.openAt))&&r.sealed?.mode==='passphrase'&&typeof r.sealed.ciphertext==='string'):[];}catch{return[];}}
export function saveReflections(rows:Reflection[]){localStorage.setItem(REFLECTION_KEY,JSON.stringify(rows));}
export function reflectionUnlocked(row:Reflection,now=Date.now()){return now>=Date.parse(row.openAt);}
export async function blessingStore(action:'get'|'put'|'delete',id:string,blob?:Blob):Promise<Blob|null>{return new Promise((resolve,reject)=>{const open=indexedDB.open('patro.birthday.blessings.v1',1);open.onupgradeneeded=()=>open.result.createObjectStore('recordings');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction('recordings',action==='get'?'readonly':'readwrite'),store=tx.objectStore('recordings'),req=action==='get'?store.get(id):action==='delete'?store.delete(id):store.put(blob,id);let result:Blob|null=null;req.onsuccess=()=>{if(action==='get'&&req.result instanceof Blob)result=req.result;};tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(tx.error);};};});}
