import { useRef,useState } from 'react';
import { eventIcs,downloadText,scheduleExistingPush,type ShareEvent } from './calendar-sharing';
import {formatPlaceInstant} from './timing';
export function ReminderActions({event}:{event:ShareEvent}) {
 const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');const card=useRef<HTMLDivElement>(null);
 async function share() { if(!card.current)return;try{const {toPng}=await import('html-to-image');await document.fonts.ready;const data=await toPng(card.current,{pixelRatio:2,backgroundColor:'#fffaf0'});const a=document.createElement('a');a.href=data;a.download='aafnai-local-timing.png';a.click();setStatus('Share card downloaded.');}catch{setStatus('Card export unavailable.');} }
 return <div><div ref={card} role="img" aria-label={`${event.title}: ${formatPlaceInstant(event.start,event.tz)} to ${formatPlaceInstant(event.end,event.tz)}`} style={{padding:20,background:'#fffaf0',color:'#172019',overflowWrap:'anywhere'}}><strong>{event.title}</strong><p>{formatPlaceInstant(event.start,event.tz)} → {formatPlaceInstant(event.end,event.tz)}</p><small>{event.url}</small></div>
 <button type="button" onClick={()=>downloadText(eventIcs(event,crypto.randomUUID()),'aafnai-local-timing.ics','text/calendar')}>ICS · ३० मिनेट अघि सूचना</button><button type="button" onClick={()=>void share()}>Share PNG</button>
 <label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> शीर्षक र समय push सेवामा पठाउन सहमत / Send title and time to existing push service</label><button type="button" disabled={!consent||busy||event.start.getTime()<Date.now()+30*60000} onClick={async()=>{setBusy(true);try{await scheduleExistingPush(event);setStatus('Scheduled. Manage/cancel at /me/reminders.');}catch(e){setStatus(e instanceof Error?e.message:'Push unavailable.');}finally{setBusy(false);}}}>Push · 30 min</button><p role="status">{status}</p><a href="/me/reminders">सूचना व्यवस्थापन · Manage reminders</a></div>;
}
