import { useEffect, useState } from 'react';
import * as A from 'astronomy-engine';
import {placeTiming} from './timing';
import type { SavedPlace } from './place';
export function sunAzimuth(instant:Date,place:SavedPlace) { const obs=new A.Observer(place.lat,place.lon,0),eq=A.Equator(A.Body.Sun,instant,obs,true,true);return A.Horizon(instant,obs,eq.ra,eq.dec,'normal').azimuth; }
export default function SunCompass({date,place}:{date:string;place:SavedPlace}) {
 const [heading,setHeading]=useState<number|null>(null),[enabled,setEnabled]=useState(false),[status,setStatus]=useState('');
 useEffect(()=>{if(!enabled)return;const handler=(event:DeviceOrientationEvent)=>{const ios=(event as DeviceOrientationEvent&{webkitCompassHeading?:number}).webkitCompassHeading;if(Number.isFinite(ios))setHeading(ios!);else if(event.absolute&&event.alpha!==null)setHeading((360-event.alpha)%360);else setStatus('Absolute heading unavailable; use bearings from true north.');};window.addEventListener('deviceorientationabsolute',handler);window.addEventListener('deviceorientation',handler);return()=>{window.removeEventListener('deviceorientationabsolute',handler);window.removeEventListener('deviceorientation',handler);};},[enabled]);
 async function enable(){try{const ctor=DeviceOrientationEvent as typeof DeviceOrientationEvent&{requestPermission?:()=>Promise<string>};if(ctor.requestPermission&&await ctor.requestPermission()!=='granted'){setStatus('दिशा अनुमति दिइएन / Permission denied.');return;}setEnabled(true);setStatus('Compass accuracy depends on device calibration; readings may use magnetic north.');}catch{setStatus('दिशा sensor उपलब्ध छैन। उत्तरबाट bearing प्रयोग गर्नुहोस् / No sensor.');}}
 let directions:{rise:number;set:number}|null=null;try{const t=placeTiming(date,place);directions={rise:sunAzimuth(t.sunrise,place),set:sunAzimuth(t.sunset,place)};}catch{}
 return <details><summary>सूर्यको दिशा · Sun compass</summary>{directions?<><p>सूर्य {directions.rise.toFixed(0)}° बाट उदाउँछ; {directions.set.toFixed(0)}° मा अस्ताउँछ / Sunrise and sunset bearings clockwise from true north.</p><svg role="img" aria-label={`Sunrise ${directions.rise.toFixed(0)} degrees from north`} viewBox="0 0 160 160" width="160"><circle cx="80" cy="80" r="65" fill="none" stroke="currentColor"/><text x="74" y="20">N</text><g transform={`rotate(${directions.rise-(heading||0)} 80 80)`}><path d="M80 28 L70 48 H76 V115 H84 V48 H90 Z" fill="#c77716"/></g></svg><button type="button" onClick={()=>void enable()} disabled={enabled}>दिशा अनुमति · Enable compass</button><p role="status">{status}</p></>:<p>यस दिनमा सूर्य उदय/अस्त हुँदैन; compass bearing उपलब्ध छैन।</p>}<p>गणना browser मा हुन्छ; page/assets cached भए offline पनि चल्छ। नदी/घाटमा उपकरणको दिशा पक्का गर्नुहोस्।</p></details>;
}
