import { useEffect } from "react";
import { adToBs, bsToAd } from "../../packages/core/src";
import { BS_MONTHS, toNepaliDigits } from "../title";
import { staticCalendarMonthBundle } from "../calendarStaticBundle";

type WeatherDay={date:string;icon:string;label?:string;temperature_max_c:number|null;temperature_min_c:number|null;precipitation_probability_max:number|null};
type CalendarDecoration={tithi:string;ns:string};
const FULL_NE_DAYS=["आइतबार","सोमबार","मंगलबार","बुधबार","बिहीबार","शुक्रबार","शनिबार"];
const NEPALI_DIGITS:Record<string,string>={"०":"0","१":"1","२":"2","३":"3","४":"4","५":"5","६":"6","७":"7","८":"8","९":"9"};
const CALENDAR_REFRESH_TOKEN="20261005-static25-v1";
function todayNepal(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function englishLabel(ad:string){const d=new Date(ad+"T00:00:00Z");if(Number.isNaN(d.getTime()))return"";return `${d.getUTCDate()}-${new Intl.DateTimeFormat("en",{month:"short",timeZone:"UTC"}).format(d)}`}
function tithiText(row:any){const p=row?.archive_panchang||row?.panchang||{},t=row?.tithi||p?.tithi||{};return String(t?.ne||t?.name_ne||t?.tithi_name_ne||p?.tithi_name_ne||"").trim()}
function nsText(row:any){const v=row?.calendars?.nepal_sambat_detail||row?.calendars?.nepal_sambat||row?.nepal_sambat||row?.ns;if(!v)return"";if(typeof v==="string")return v.replace(/^नेपाल\s*संवत्\s*/i,"").trim();const f=String(v.formatted_ne||v.formatted||"").replace(/^नेपाल\s*संवत्\s*/i,"").trim();if(f)return f;const month=v.month?.dev||v.month?.ne||v.month_ne||v.month_name_ne||v.month?.roman||"",day=v.day??v.tithi_day??v.date_day??v.tithi?.day;if(day!=null)return `${month?month+" ":""}${toNepaliDigits(day)}`.trim();const year=v.year??v.ns_year;return year?toNepaliDigits(year):""}
function rowDate(row:any){return String(row?.calendars?.gregorian_ad||row?.ad||row?.date||row?.query_date||"")}
function parseNumber(text:string){const n=Number(text.replace(/[०-९]/g,d=>NEPALI_DIGITS[d]||d).replace(/[^0-9]/g,""));return Number.isInteger(n)?n:NaN}
function visibleBsCursor(){const route=location.pathname.match(/^\/calendar\/(\d{4})\/(\d{1,2})(?:\/|$)/);if(route)return{year:Number(route[1]),month:Number(route[2])};try{const bs=adToBs(todayNepal());return{year:bs.year,month:bs.month}}catch{return null}}
function richCellDate(cell:Element){const explicit=cell.getAttribute("data-ad")||"";if(/^\d{4}-\d{2}-\d{2}$/.test(explicit))return explicit;const bsNode=cell.querySelector<HTMLElement>(".pc-bs"),cursor=visibleBsCursor(),day=bsNode?parseNumber(bsNode.textContent||""):NaN;if(cursor&&day>=1&&day<=32){try{return bsToAd({year:cursor.year,month:cursor.month,day})}catch{}}return""}
function collectVisibleDates(){const dates=new Set<string>();document.querySelectorAll(".rh-grid .rh-cell").forEach(cell=>{const ad=richCellDate(cell);if(ad)dates.add(ad)});document.querySelectorAll<HTMLAnchorElement>('.ap-month-grid a.ap-day[href^="/date/"]').forEach(cell=>{const ad=(cell.getAttribute("href")||"").slice(6);if(/^\d{4}-\d{2}-\d{2}$/.test(ad))dates.add(ad)});return[...dates].sort()}
function decorateHomepageDate(){const path=location.pathname.replace(/\/+$/,"")||"/";if(path!=="/"&&path!=="/today")return;const ad=todayNepal();try{const bs=adToBs(ad),label=`${toNepaliDigits(bs.day)} ${BS_MONTHS[bs.month-1]} ${toNepaliDigits(bs.year)}`;document.querySelectorAll<HTMLElement>(".rh-hero h1,.rh-today h1,.ap-today-card h1").forEach(n=>{if(n.textContent!==label)n.textContent=label})}catch{}const weekday=FULL_NE_DAYS[new Date(ad+"T00:00:00Z").getUTCDay()];document.querySelectorAll<HTMLElement>(".rh-hero .rh-kicker,.rh-today>.rh-kicker").forEach(n=>n.textContent=`आज · ${weekday}`)}
function weatherTitle(f:WeatherDay){const max=f.temperature_max_c==null?"":`${Math.round(f.temperature_max_c)}°C`,min=f.temperature_min_c==null?"":`${Math.round(f.temperature_min_c)}°C`,rain=f.precipitation_probability_max==null?"":`${Math.round(f.precipitation_probability_max)}% वर्षा`;return[f.label||"काठमाडौं मौसम",max&&min?`${min}–${max}`:max||min,rain,"Open-Meteo"].filter(Boolean).join(" · ")}
function decorate(weather:Map<string,WeatherDay>,calendar:Map<string,CalendarDecoration>){decorateHomepageDate();const today=calendar.get(todayNepal()),facts=document.querySelectorAll<HTMLElement>(".rh-today-facts > div b");if(today?.tithi&&facts[0]&&(!facts[0].textContent||facts[0].textContent.trim()==="—"))facts[0].textContent=today.tithi;if(today?.ns&&facts[1]&&(!facts[1].textContent||facts[1].textContent.trim()==="—"))facts[1].textContent=today.ns;
 for(const cell of document.querySelectorAll<HTMLElement>(".rh-grid .rh-cell")){const ad=richCellDate(cell);if(!ad)continue;cell.dataset.ad=ad;const info=calendar.get(ad),adNode=cell.querySelector<HTMLElement>(".pc-ad");if(adNode){const label=englishLabel(ad);if(adNode.textContent!==label)adNode.textContent=label}const t=cell.querySelector<HTMLElement>(".pc-tithi"),ns=cell.querySelector<HTMLElement>(".pc-ns");if(t&&info?.tithi)t.textContent=info.tithi;if(ns&&info?.ns)ns.textContent=info.ns;let icon=cell.querySelector<HTMLElement>(".pc-weather");const forecast=weather.get(ad);if(!forecast){icon?.remove();continue}if(!icon){icon=document.createElement("span");icon.className="pc-weather";icon.setAttribute("aria-hidden","true");const top=cell.querySelector<HTMLElement>(".pc-top");top?top.insertBefore(icon,top.querySelector(".pc-ad")):cell.prepend(icon)}icon.textContent=forecast.icon;icon.title=weatherTitle(forecast)}
}
export function CalendarCellEnhancer(){useEffect(()=>{let stopped=false,calendarRange="",refreshTimer=0,retryTimer=0,retries=0;const weather=new Map<string,WeatherDay>(),calendar=new Map<string,CalendarDecoration>();const ingest=(rows:any[])=>{let useful=0;for(const row of rows){const ad=rowDate(row);if(!/^\d{4}-\d{2}-\d{2}$/.test(ad))continue;const t=tithiText(row),ns=nsText(row);if(!t&&!ns)continue;calendar.set(ad,{tithi:t,ns});useful++}return useful};const complete=(dates:string[])=>dates.every(ad=>{const x=calendar.get(ad);return!!(x?.tithi&&x?.ns)});
 const fetchCalendar=async()=>{if(stopped)return;const dates=collectVisibleDates();if(!dates.length)return;const start=dates[0],end=dates.at(-1)!,key=`${start}|${end}`;if(key===calendarRange)return;calendarRange=key;try{let useful=0;const cursor=visibleBsCursor();if(cursor){const local=await staticCalendarMonthBundle(cursor.year,cursor.month);useful+=ingest(local?.days||[]);decorate(weather,calendar)}if(!complete(dates)){try{const response=await fetch(`/api/v1/sync?start=${encodeURIComponent(start)}&end=${encodeURIComponent(end)}&fresh=${CALENDAR_REFRESH_TOKEN}`,{headers:{accept:"application/json"},cache:"no-store"});if(response.ok){const body=await response.json();useful+=ingest(Array.isArray(body?.days)?body.days:[])}}catch{}}if(!complete(dates)&&cursor){try{const response=await fetch(`/api/v1/calendar/${cursor.year}/${cursor.month}?calendar=bs`,{headers:{accept:"application/json"}});if(response.ok){const body=await response.json();useful+=ingest(Array.isArray(body?.days)?body.days:[])}}catch{}}if(!useful)throw new Error("calendar_facts_missing");retries=0;decorate(weather,calendar)}catch{calendarRange="";if(!stopped&&retries<2){retries++;clearTimeout(retryTimer);retryTimer=window.setTimeout(()=>void fetchCalendar(),1000*retries)}}};
 const run=()=>{if(stopped)return;decorate(weather,calendar);clearTimeout(refreshTimer);refreshTimer=window.setTimeout(()=>void fetchCalendar(),50)};const observer=new MutationObserver(run);observer.observe(document.body,{subtree:true,childList:true});run();fetch("/api/v1/weather/daily?days=16",{headers:{accept:"application/json"}}).then(r=>r.ok?r.json():Promise.reject()).then(body=>{for(const item of Array.isArray(body?.days)?body.days:[])if(item?.date)weather.set(String(item.date),item);run()}).catch(()=>undefined);return()=>{stopped=true;clearTimeout(refreshTimer);clearTimeout(retryTimer);observer.disconnect()}},[]);return null}
