import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,statSync,existsSync} from 'node:fs';
import {route,sitemap,dateIndex,dateAt,facts,midnight,TOTAL,DAYS,SHARD} from './worker.mjs';
import cities from './cities.json' with {type:'json'};
assert.equal(TOTAL,1000000);assert.equal(cities.length,50);assert.equal(new Set(cities.map(c=>c.slug)).size,50);
assert.equal(dateIndex('2026-02-29'),-1);assert.equal(dateIndex('2024-02-29'),dateIndex('2024-02-28')+1);assert.equal(dateIndex('1982-07-11'),-1);assert.equal(dateIndex('2037-04-14'),-1);
const ny=cities.find(c=>c.name==='New York');
assert.equal((midnight('2026-03-09',ny.tz)-midnight('2026-03-08',ny.tz))/3600000,23);
assert.equal((midnight('2026-11-02',ny.tz)-midnight('2026-11-01',ny.tz))/3600000,25);
let count=0,bytes=0;const start=performance.now();
for(let n=0;n<TOTAL/SHARD;n++){const xml=sitemap(n),urls=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]);assert.equal(urls.length,SHARD);assert.ok(Buffer.byteLength(xml)<50000000);for(let j=0;j<urls.length;j++){const i=n*SHARD+j;assert.equal(urls[j],`https://aafnaipatro.com/atlas/${cities[Math.floor(i/DAYS)].slug}/${dateAt(i%DAYS)}`);}count+=urls.length;bytes+=Buffer.byteLength(xml);}
let samples=0,times=[];for(const c of cities){for(const d of ['1982-07-12','2000-02-29','2026-03-08','2026-10-09','2026-11-01','2037-04-13']){const st=performance.now(),f=facts(c,d);times.push(performance.now()-st);assert.ok(f.start<f.end);assert.ok(f.illumination>=0&&f.illumination<=1);for(const event of [f.rise,f.set])if(event)assert.ok(event>=f.start&&event<f.end);samples++;}}
const ktm=facts(cities[0],'2026-10-09');for(const [key,expected] of [['rise',360],['set',1061]]){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(ktm[key]).split(':').map(Number);assert.ok(Math.abs(parts[0]*60+parts[1]-expected)<=2);}
const polar=facts({name:'Tromso',lat:69.6492,lon:18.9553,tz:'Europe/Oslo'},'2026-06-21');assert.equal(polar.rise,null);assert.equal(polar.set,null);
const request=p=>new Request('https://aafnaipatro.com'+p);
for(const p of ['/atlas/','/atlas/kathmandu','/atlas/kathmandu/year/2026','/atlas/kathmandu/month/2026-10','/atlas/kathmandu/2026-10-09','/atlas/kathmandu/2026-10-09/calendar.ics','/sitemap-atlas.xml','/sitemap-atlas-999.xml'])assert.equal((await route(request(p))).status,200);
for(const p of ['/atlas/fake/2026-10-09','/atlas/kathmandu/2026-02-29','/sitemap-atlas-1000.xml','/sitemap-atlas-01.xml','/atlas/kathmandu/month/2026-13'])assert.equal((await route(request(p))).status,404);
const html=await (await route(request('/atlas/kathmandu/2026-10-09'))).text();assert.ok(html.includes('<link rel="canonical" href="https://aafnaipatro.com/atlas/kathmandu/2026-10-09">'));assert.ok(html.includes('index,follow'));assert.ok(html.includes('Sunrise'));assert.ok(html.includes('application/ld+json'));assert.notEqual(html,await(await route(request('/atlas/tokyo/2026-10-09'))).text());
const oldRobots=readFileSync(existsSync('/tmp/patro-robots-before.txt')?'/tmp/patro-robots-before.txt':new URL('../../public/robots.txt',import.meta.url),'utf8'),oldMap=readFileSync(existsSync('/tmp/patro-sitemap-before.xml')?'/tmp/patro-sitemap-before.xml':new URL('../../public/sitemap.xml',import.meta.url),'utf8');const env={ORIGIN:{fetch:async r=>new Response(new URL(r.url).pathname==='/robots.txt'?oldRobots:oldMap)}};
const robots=await(await route(request('/robots.txt'),env)).text();assert.ok(robots.startsWith(oldRobots));assert.ok(robots.includes('Sitemap: https://aafnaipatro.com/sitemap-atlas.xml'));
const map=await(await route(request('/sitemap.xml'),env)).text();for(const m of oldMap.matchAll(/<loc>(.*?)<\/loc>/g))assert.ok(map.includes(m[0]));assert.equal([...map.matchAll(/sitemap-atlas-\d+\.xml/g)].length,1000);
times.sort((a,b)=>a-b);const report={inventory:count,sitemaps:1000,storedHtmlFiles:0,newDatabaseRows:0,generatedXmlBytes:bytes,astronomySamples:samples,medianComputeMs:times[Math.floor(times.length/2)],p95ComputeMs:times[Math.floor(times.length*.95)],bundleBytes:statSync(new URL('./bundle.mjs',import.meta.url)).size,elapsedMs:performance.now()-start,existingSitemapEntriesPreserved:true,dstAndPolarTestsPassed:true};writeFileSync(new URL('./verification.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
