// Editorial facts checked 10 October 2026. Nepal sait instants are not overseas muhurta.
export const notice = 'https://giwmscdnone.gov.np/media/pdf_upload/Dashain%202083_dzoktsj.pdf';
export const cities = [['Kathmandu','Asia/Kathmandu'],['Sydney','Australia/Sydney'],['Doha','Asia/Qatar'],['Tokyo','Asia/Tokyo'],['New York','America/New_York']];
export const saits = [
 {name:'घटस्थापना · Ghatasthapana',icon:'kalash',bs:'असोज २५, २०८३',at:'2026-10-11T11:47:00+05:45',note:'कलश स्थापना र जमरा राख्ने शुभसाइत।'},
 {name:'विजया दशमी · Dashain Tika',icon:'tika',bs:'कात्तिक ४, २०८३',at:'2026-10-21T10:26:00+05:45',note:'देवी विसर्जन बिहान ८:४९ बजे। टीका ग्रहण गर्ने व्यक्ति पश्चिम फर्कने। समितिका अनुसार दिनभर टीका लिन सकिन्छ।'}
];
const esc = x => String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function icon(kind='lamp') {
 const paths={lamp:'<path d="M5 16h22c-2 8-20 8-22 0Z"/><path d="M16 14c-6-4-1-9 1-11 0 4 6 7-1 11Z"/>',kalash:'<path d="M9 14h14l2 7c0 9-18 9-18 0Z"/><path d="M10 14c-4-6 0-7 6-3 6-4 10-3 6 3"/><path d="M12 10c-2-9 10-9 8 0"/>',tika:'<circle cx="16" cy="12" r="5"/><path d="M8 23h16M6 27h20M7 17l-3 5M25 17l3 5"/>',flower:'<path d="M16 28v-9M16 24l-7-4M16 24l7-4"/><circle cx="16" cy="12" r="4"/><path d="M12 8c-7-9-12 5-4 6-7 8 6 13 8 4 2 9 15 4 8-4 8-1 3-15-4-6-1-9-7-9-8 0Z"/>',temple:'<path d="M3 15h26L16 5ZM6 23h20l-10-6ZM9 29V23h14v6M16 5V2"/>'};
 return `<svg class="fest-icon" viewBox="0 0 32 32" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round">${paths[kind]||paths.lamp}</svg>`;
}
export function cityTime(at,zone) {return new Intl.DateTimeFormat('en-GB',{timeZone:zone,weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true,timeZoneName:'short'}).format(new Date(at));}
function timeCard(s) {return `<section class="fest-sait"><div class="fest-title">${icon(s.icon)}<h3>${esc(s.name)}</h3></div><p>${esc(s.bs)}</p><time datetime="${s.at}">${esc(cityTime(s.at,'Asia/Kathmandu'))}</time><p>${esc(s.note)}</p><div class="fest-count" data-fest-countdown="${s.at}" role="timer" aria-label="Countdown to ${esc(s.name)}">साइतसम्मको समय गणना हुँदैछ…</div><div class="fest-city">${cities.map(([name,zone])=>`<div><b>${name}</b><span>${esc(cityTime(s.at,zone))}</span></div>`).join('')}</div><a href="${notice}" target="_blank" rel="noopener">समितिको २०८३ आधिकारिक साइत विज्ञप्ति ↗</a></section>`;}
const nav = [
 ['प्रतिपदा','शैलपुत्री','घटस्थापना: कलश स्थापना, देवी आवाहन र जमरा रोपण। सफा पूजा स्थान तयार गर्ने।'],
 ['द्वितीया','ब्रह्मचारिणी','नित्य दुर्गा पूजा, संयम र साधनाको स्मरण। जमरा जाँच्ने र परिवारको परम्पराअनुसार पूजा गर्ने।'],
 ['तृतीया','चन्द्रघण्टा','देवी आराधना र प्रार्थना। घण्टा, दीप र पुष्पको प्रयोग घरको चलनअनुसार हुन्छ।'],
 ['चतुर्थी','कुष्माण्डा','सृष्टि र ऊर्जाको प्रतीक देवीको स्मरण; नित्य पूजा र जमराको हेरचाह जारी राख्ने।'],
 ['पञ्चमी','स्कन्दमाता','मातृत्व र संरक्षणको स्मरण। २०८३ असोज २९ / October 15 मा पचली भैरव यात्रा सूचीकृत छ।'],
 ['षष्ठी','कात्यायनी','देवीको शक्ति र साहसको स्मरण; फूलपातीका लागि पूजा सामग्री तयार गर्ने।'],
 ['सप्तमी','कालरात्रि','फूलपाती: असोज ३१ / October 17। तुलजा भवानी यात्रा ७:३७ र स्थिरासन १०:३९ बिहान (नेपाल समय)।'],
 ['अष्टमी','महागौरी','महाअष्टमी: कात्तिक १ / October 18; त्यही रात कालरात्रि। कात्तिक २ / October 19 मा पनि अष्टमी तिथि छ।'],
 ['नवमी','सिद्धिदात्री','महानवमी: कात्तिक ३ / October 20। घरको परम्पराअनुसार शक्ति पूजा तथा औजार/वाहन पूजा; अर्को दिन टीका।']
];
const templeSource='https://radionepalonline.com/en/2024/10/10/391456.html';
const temples=[
 ['दक्षिणकाली','Dakshinkali · Pharping','कालीको शक्तिपीठ। फूलपाती र नवरात्रमा देवी दर्शन; विशेषतः मङ्गलबार र शनिबार नियमित भक्तजनको चाप।','दर्शन, फूल/दीप अर्पण र परिवारको परम्पराअनुसार पूजा। पशुबलिको परम्परा पनि छ; सहभागी हुने/नहुने निर्णय आफ्नो आस्थाअनुसार।','https://ntb.gov.np/en/dakshinkali-'],
 ['पालाञ्चोक भगवती','Palanchowk · Kavre','डाँडामा रहेको भगवती मन्दिर; अठार हातको दुर्गाको मूर्ति प्रसिद्ध छ। नवरात्रमा देवी दर्शन गर्ने परम्परा।','दर्शन र परिवारको मंगलका लागि पूजा; स्थानीय पुजारीसँग पूजा विधि बुझ्ने। लामिडाँडाबाट जाने सडक र यातायातको अवस्था यात्रा अघि बुझ्ने।','https://ntb.gov.np/palanchowk-bhagawati--kavre'],
 ['गुह्येश्वरी','Guhyeshwari · Pashupati area','फूलपातीमा दर्शनार्थी पुग्ने काठमाडौंका देवीस्थलमध्ये एक।','दर्शन र देवी आराधना; परिसरको प्रवेश तथा पूजा नियम पालना गर्ने।',templeSource],
 ['मैतीदेवी','Maitidevi · Kathmandu','नवरात्र/फूलपातीमा देवी दर्शनका लागि जाने उपत्यकाको मन्दिर।','दर्शन, दीप र पुष्प अर्पण; लाइन तथा स्थानीय सेवकको निर्देशन पालना गर्ने।',templeSource],
 ['नक्साल भगवती','Naxal Bhagawati · Kathmandu','देवी दर्शनका लागि भक्तजन जाने काठमाडौंको भगवती मन्दिर।','घरको परम्पराअनुसार पूजा र दर्शन। पुजारीसँग विशेष पूजा उपलब्धता बुझ्ने।',templeSource],
 ['शोभा भगवती','Shova Bhagawati · Kathmandu','फूलपातीमा दर्शन हुने उपत्यकाको देवीस्थल।','देवी दर्शन र प्रार्थना; भीड र यातायातका लागि अतिरिक्त समय राख्ने।',templeSource],
 ['भद्रकाली','Bhadrakali · Kathmandu','नवरात्रमा देवी आराधनाका लागि पुग्ने शक्तिस्थल।','दर्शन र फूल/दीप अर्पण; मन्दिरको दैनिक समय स्थानीय व्यवस्थापनबाट बुझ्ने।',templeSource],
 ['चण्डेश्वरी','Chandeshwari · Banepa','काभ्रेको देवी मन्दिर; फूलपातीमा भक्तजन दर्शन गर्न पुग्ने स्थल।','भगवती दर्शन र पूजा। पालाञ्चोकसँग एउटै दिन यात्रा गर्ने भए दूरी र सडकको अवस्था पहिले बुझ्ने।',templeSource]
];
function photo(file,name,author,version) {return `<figure class="fest-photo"><img src="https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}?width=960" alt="${esc(name)}" width="960" height="720" loading="lazy" decoding="async"><figcaption>${esc(name)} · Photo: ${esc(author)} · <a href="https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file)}">Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by-sa/${version}/">CC BY-SA ${version}</a> · original photograph, displayed to fit</figcaption></figure>`;}
export function festivalFeature(slug,year=2083) {
 if(Number(year)!==2083)return '';
 const dash=['dashain','ghatasthapana','phulpati','maha-ashtami','maha-navami'].includes(slug), tihar=['tihar','laxmi-puja','bhai-tika'].includes(slug);
 if(!dash&&!tihar)return '';
 const head=`<link rel="stylesheet" href="/festive/festive-2083.css"><div class="festive-2083" data-festive-guide><header class="fest-hero"><p class="fest-kicker">आफ्नै पात्रो · FESTIVAL GUIDE 2083 / 2026</p><h2>${icon(dash?'kalash':'lamp')}${dash?'दशैं · घर, आस्था र आशीर्वाद':'तिहार · उज्यालो र आत्मीयता'}</h2><p>${dash?'घटस्थापनादेखि टीकासम्म: साइत, विश्वका शहरको समय र नवरात्र यात्रा।':'November 7–11 · काग तिहारदेखि भाइटीकासम्मको तयारी।'}</p><nav aria-label="Festival guide"><a href="/festivals/dashain/2083">दशैं</a><a href="/festivals/tihar/2083">तिहार</a>${dash?'<a href="#navadurga">नवदुर्गा</a><a href="#temple-guide">मन्दिर दर्शन</a>':''}<a href="#fest-sources">स्रोत</a></nav></header>`;
 if(tihar)return `${head}<section class="fest-panel"><h2>${icon()}तिहार २०८३ · November 7–11</h2><p>लक्ष्मी पूजा: कात्तिक २२ / Sunday, November 8। भाइटीका: कात्तिक २५ / Wednesday, November 11।</p><div class="fest-grid">${[['लक्ष्मी पूजा','November 8','घर सफा गर्ने, प्रवेशद्वार सजाउने, दीप र लक्ष्मी पूजाको तयारी।'],['भाइटीका','November 11','सप्तरङ्गी टीका, मखमली माला र दाजुभाइ–दिदीबहिनीको भेटको तयारी।']].map(([n,d,t])=>`<section class="fest-sait"><h3>${icon(n==='भाइटीका'?'tika':'lamp')}${n}</h3><p>${d}, 2026</p><b>साइत घोषणा प्रतीक्षामा · Sait awaiting announcement</b><p>${t}</p><p>२०८३ को आधिकारिक समय पुष्टि भएपछि मात्र समय र countdown थपिनेछ। अघिल्लो वर्षको साइत यहाँ प्रयोग गरिएको छैन।</p><a href="https://npns.gov.np/">समितिका नयाँ सूचना हेर्नुहोस् ↗</a></section>`).join('')}</div><h3>यमपञ्चकको परम्परागत क्रम</h3><p>काग तिहार → कुकुर तिहार → गाई/लक्ष्मी पूजा → गोवर्धन/म्ह पूजा → भाइटीका। तिथिका कारण दुई पूजा एकै मितिमा पर्न सक्छन्; “पाँच दिन” लाई पाँच समान २४ घण्टाको खण्ड नमान्नुहोस्। २०८३ कुकुर तिहार र लक्ष्मी पूजा November 8 मा; गोवर्धन पूजा र नेपाल संवत् ११४७ प्रारम्भ November 10 मा सूचीकृत छन्।</p><p>माला, पूजासामग्री र परिवारको समय अगाडि मिलाउनुहोस्। विदेशमा बस्दा स्थानीय मन्दिरको observance मिति सोध्नुहोस्; नेपालमा घोषित साइतको clock conversion स्थानीय मुहूर्त होइन।</p></section>${photo('Sister lighting traditional lamp during Tihar festival.jpg','तिहारमा परम्परागत दीप प्रज्वलन (2020)','Mithunkunwar9','4.0')}<section id="fest-sources" class="fest-panel"><h2>स्रोत र अद्यावधिक</h2><p>Checked: October 10, 2026 (Nepal). <a href="https://npns.gov.np/">नेपाल पञ्चाङ्ग निर्णायक विकास समिति</a> · <a href="https://www.ratopati.com/story/543999/calendar-for-2083-bs-dashain-tika-on-kartik-4th-when-is-tihar">२०८३ पात्रोका प्रकाशित पर्व मिति</a></p></section></div><script defer src="/festive/festive-2083.js"></script>`;
 return `${head}<section class="fest-panel"><h2>शुभसाइत · Live countdown</h2><div class="fest-grid">${saits.map(timeCard).join('')}</div><p class="fest-note">सबै शहरका समय नेपालमा घोषित एउटै साइतको clock conversion हुन्। यो शहरको स्थानीय पूजा मुहूर्त होइन। New York मा घटस्थापनाको यही क्षण October 11, बिहान 2:02 र टीकाको क्षण October 21, बिहान 12:41 पर्छ। स्थानीय पर्व पालना मन्दिर/पुजारीसँग पुष्टि गर्नुहोस्।</p></section><section id="navadurga" class="fest-panel"><h2>${icon('flower')}नवरात्र · नवदुर्गा दैनिक मार्गदर्शन</h2><p>तिथिअनुसार नवदुर्गाका नौ रूपको परम्परागत क्रम। यो वर्ष अष्टमी दुई civil dates मा फैलिएकोले एक देवी = एक अंग्रेजी मिति भनेर क्रम मिलाइएको छैन। घर, समुदाय र सम्प्रदायअनुसार पूजा फरक हुन सक्छ।</p><div class="fest-grid">${nav.map(([t,n,d],i)=>`<section class="fest-day"><span class="fest-number">${i+1}</span><h3>${esc(n)}</h3><b>${esc(t)}</b><p>${esc(d)}</p></section>`).join('')}</div></section><div class="fest-grid">${photo('Dakshinkali Temple Kathmandu Nepal.jpg','दक्षिणकाली मन्दिर (2011)','सरोज कुमार ढकाल','3.0')}${photo('Palanchowk Bhagawati Temple.jpg','पालाञ्चोक भगवती मन्दिर (2019)','Gaurav Dhwaj Khadka','4.0')}</div><section id="temple-guide" class="fest-panel"><h2>${icon('temple')}दक्षिणकालीदेखि पालाञ्चोक · मन्दिर दर्शन</h2><p>तलका विवरण सामान्य दर्शन/पूजा परम्परा र प्रकाशित स्थान विवरण हुन्। २०८३ को मन्दिरविशेष दैनिक आरती, टिकट वा दर्शन समयको आधिकारिक तालिका प्राप्त भएको छैन; यात्रा अघि व्यवस्थापनसँग बुझ्नुहोस्।</p><div class="fest-grid">${temples.map(([n,l,d,a,s])=>`<section class="fest-day"><h3>${icon('temple')}${n}</h3><p class="fest-location">${l}</p><p>${d}</p><h4>के गर्ने / यात्रा तयारी</h4><p>${a}</p><a href="${s}" target="_blank" rel="noopener">स्थान/परम्पराको स्रोत ↗</a><p><a href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(l)}" target="_blank" rel="noopener">नक्सामा खोज्नुहोस् ↗</a></p></section>`).join('')}</div></section><section id="fest-sources" class="fest-panel"><h2>स्रोत र अद्यावधिक</h2><p>Checked: October 10, 2026 (Nepal). साइत: <a href="${notice}">नेपाल पञ्चाङ्ग निर्णायक विकास समिति — २० असोज २०८३ विज्ञप्ति</a>। मन्दिर विवरण: Nepal Tourism Board; दर्शन परम्परा: Radio Nepal / RSS (2024 report, not a 2026 timetable).</p><p><a href="/festivals/tihar/2083">तिहारको तयारी हेर्नुहोस् →</a></p></section></div><script defer src="/festive/festive-2083.js"></script>`;
}
