import { access, copyFile, mkdir, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
const root=process.cwd(); const spaShell=resolve(root,"dist/index.html"); const requiredSpaShells=["tools/index.html","settings/community/index.html","admin/community-suites/index.html","jyotish/janma-patro/index.html","jyotish/matchmaking/index.html"]; const requiredStaticPages=["samudaya/index.html","samudaya/lhosar/index.html","samudaya/tharu/index.html","samudaya/mithila/index.html","samudaya/kirat/index.html","samudaya/hijri/index.html","samudaya/chakra/index.html","nepal-sambat/mandala/index.html","nepali-typing/index.html"];
async function exists(path){try{await access(path);return true;}catch{return false;}}
if(!(await exists(spaShell)))throw new Error("doctor: dist/index.html is missing; Vite did not produce the canonical root SPA shell"); const shellHtml=await readFile(spaShell,"utf8"); if(!/\/assets\//.test(shellHtml)||/\/astro\/assets\//.test(shellHtml))throw new Error("doctor: root SPA bundle must load from /assets/, never /astro/assets/");
const repaired=[]; for(const relative of requiredSpaShells){const target=resolve(root,"dist",relative);if(!(await exists(target))){await mkdir(dirname(target),{recursive:true});await copyFile(spaShell,target);repaired.push(relative);}}
const missingStatic=[]; for(const relative of requiredStaticPages)if(!(await exists(resolve(root,"dist",relative))))missingStatic.push(relative); if(missingStatic.length)throw new Error("doctor: required static pages missing: "+missingStatic.join(", "));
const config=JSON.parse(await readFile(resolve(root,"wrangler.jsonc"),"utf8")); if(config.name!=="patro")throw new Error("doctor: production Worker name must be patro"); if(config.main!=="worker/connected-entry.ts")throw new Error("doctor: production Worker entry must be worker/connected-entry.ts"); if(config.preview_urls!==false)throw new Error("doctor: production preview_urls must be false"); if(config.assets?.directory!=="./dist"||config.assets?.binding!=="ASSETS")throw new Error("doctor: Workers Static Assets must bind ASSETS to ./dist"); if(!(config.d1_databases||[]).some((db)=>db.binding==="DB"))throw new Error("doctor: required D1 binding DB is missing"); if(!(config.routes||[]).some((route)=>route.pattern==="aafnaipatro.com"&&route.custom_domain===true))throw new Error("doctor: production custom domain aafnaipatro.com is missing"); if(Array.isArray(config.services)&&config.services.some((service)=>service?.binding==="PATRO_API"))throw new Error("doctor: obsolete Pages service binding must not be part of Worker production");
console.log(JSON.stringify({ok:true,repaired,verified:[...requiredSpaShells,...requiredStaticPages],canonicalShell:"dist/index.html",assetBase:"/assets/",runtime:"cloudflare-worker-static-assets",worker:"patro",workerEntry:"worker/connected-entry.ts",assetDirectory:"./dist",d1Binding:"DB",customDomain:"aafnaipatro.com",previewUrls:false,kvRequired:false},null,2));
