import { r2CalendarByAd,r2CalendarByBs,r2CalendarMonth,r2CalendarRange,type CalendarBackupEnv } from "./calendar-backup";
type Env=CalendarBackupEnv&{DB?:any;CALENDAR_COVERAGE_START?:string;CALENDAR_COVERAGE_END?:string;CALENDAR_SOURCE_VERSION?:string};
const CACHE="public, max-age=60, s-maxage=3600, stale-while-revalidate=86400",LONG="public, max-age=300, s-maxage=86400, stale-while-revalidate=604800";
function json(body:any,status=200,cache=CACHE,source?:string){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":cache,"x-content-type-options":"nosniff","x-patro-backend":"calendar-tier",...(source?{"x-patro-calendar-source":source}:{})}})}
function validDate(v:any):v is string{if(typeof v!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const[y,m,d]=v.split("-").map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function unwrap(row:any){if(!row)return null;let v=row.payload??row;if(typeof v==="string"){try{v=JSON.parse(v)}catch{return null}}if(v?.payload&&(v.payload.ad||v.payload.bs))v={...v.payload,ad:v.payload.ad||v.ad_date};return v}
function tag(row:any,source:"d1"|"r2"){const v=unwrap(row);return v?{...v,__calendar_source:source}:null}
async function d1(env:Env,sql:string,b:any[]=[]){if(!env.DB)return[];try{const out=await env.DB.prepare(sql).bind(...b).all();return(out.results||[]).map((r:any)=>tag(r,"d1")).filter(Boolean)}catch{return[]}}
function source(row:any){return row?.__calendar_source==="r2"?"r2":"d1"}
function merge(primary:any[],fallback:any[]){const map=new Map<string,any>();for(const row of fallback){const v=tag(row,"r2");if(v?.ad)map.set(v.ad,v)}for(const row of primary)if(row?.ad)map.set(row.ad,row);return[...map.values()].sort((a,b)=>String(a.ad).localeCompare(String(b.ad)))}
async function byAd(env:Env,date:string){const rows=await d1(env,"select payload from content_records where table_name='astronomy_calendar_map' and record_key=?1 limit 1",[date]);if(rows[0])return rows[0];const r=await r2CalendarByAd(env,date);return r?tag(r,"r2"):null}
async function byBs(env:Env,y:number,m:number,day:number){const rows=await d1(env,"select payload from content_records where table_name='astronomy_calendar_map' and coalesce(json_extract(payload,'$.payload.bs.year'),json_extract(payload,'$.bs.year'))=?1 and coalesce(json_extract(payload,'$.payload.bs.month'),json_extract(payload,'$.bs.month'))=?2 and coalesce(json_extract(payload,'$.payload.bs.day'),json_extract(payload,'$.bs.day'))=?3 limit 1",[y,m,day]);if(rows[0])return rows[0];const r=await r2CalendarByBs(env,y,m,day);return r?tag(r,"r2"):null}
async function monthRows(env:Env,mode:"bs"|"ad",y:number,m:number){let rows:any[]=[];if(mode==="bs")rows=await d1(env,"select payload from content_records where table_name='astronomy_calendar_map' and coalesce(json_extract(payload,'$.payload.bs.year'),json_extract(payload,'$.bs.year'))=?1 and coalesce(json_extract(payload,'$.payload.bs.month'),json_extract(payload,'$.bs.month'))=?2 order by record_key",[y,m]);else{const start=`${y}-${String(m).padStart(2,"0")}-01`,ny=m===12?y+1:y,nm=m===12?1:m+1;rows=await d1(env,"select payload from content_records where table_name='astronomy_calendar_map' and record_key>=?1 and record_key<?2 order by record_key",[start,`${ny}-${String(nm).padStart(2,"0")}-01`])}if(rows.length>=27)return rows;const r2=await r2CalendarMonth(env,mode,y,m);return merge(rows,r2)}
async function rangeRows(env:Env,start:string,end:string,expected:number){const rows=await d1(env,"select payload from content_records where table_name='astronomy_calendar_map' and record_key>=?1 and record_key<=?2 order by record_key limit 62",[start,end]);if(rows.length>=expected)return rows;return merge(rows,await r2CalendarRange(env,start,end))}
function calendarShape(c:any){return{ad:c.ad,bs:c.bs,nepal_sambat:c.ns,panchang:c.panchang,source:source(c)==="r2"?"Cloudflare R2 calendar backup":"Cloudflare D1 astronomy archive"}}
function syncShape(date:string,c:any){return{success:true,query_date:date,calendars:{gregorian_ad:date,bikram_sambat:c.bs?.formatted||"",nepal_sambat:c.ns?.formatted||"",bikram_sambat_detail:c.bs||null,nepal_sambat_detail:c.ns||null},tithi:c.panchang?.tithi||null,archive_panchang:c.panchang||null,calendar_source:source(c)}}
export async function calendarTierResponse(request:Request,env:Env):Promise<Response|null>{if(request.method!=="GET")return null;const url=new URL(request.url),path=url.pathname;
 if(path==="/api/v1/sync"){const start=url.searchParams.get("start"),end=url.searchParams.get("end");if(start!=null||end!=null){if(!validDate(start)||!validDate(end))return json({success:false,error:"invalid_range"},400);const expected=Math.floor((Date.parse(end+"T00:00:00Z")-Date.parse(start+"T00:00:00Z"))/86400000)+1;if(expected<1||expected>62)return json({success:false,error:"range_limit_exceeded",max_days:62},400);const rows=await rangeRows(env,start,end,expected);if(!rows.length)return null;const days=rows.map(r=>syncShape(r.ad,r));return json({success:true,start_date:start,end_date:end,requested_days:expected,returned_days:days.length,days,coverage:{ad_start:env.CALENDAR_COVERAGE_START||"1826-04-11",ad_end:env.CALENDAR_COVERAGE_END||"2037-04-13",source_version:env.CALENDAR_SOURCE_VERSION||"patro-archive-v79",rows:77070}},200,CACHE,source(rows[0]))}const date=url.searchParams.get("date")||today();if(!validDate(date))return json({success:false,error:"invalid_date"},400);const row=await byAd(env,date);return row?json(syncShape(date,row),200,CACHE,source(row)):null}
 const mm=path.match(/^\/api\/v1\/calendar\/(\d{4})\/(\d{1,2})$/);if(mm){const y=Number(mm[1]),m=Number(mm[2]),mode=(url.searchParams.get("calendar")||((y>2050)?"bs":"ad")) as "bs"|"ad";if(m<1||m>12||!['bs','ad'].includes(mode))return json({ok:false,error:"invalid_month"},400);const rows=await monthRows(env,mode,y,m);if(!rows.length)return null;return json({ok:true,calendar:mode,year:y,month:m,count:rows.length,days:rows.map(calendarShape)},200,LONG,source(rows[0]))}
 if(path==="/api/v1/today"||path==="/api/v1/panchang"){const date=url.searchParams.get("date")||today();if(!validDate(date))return json({ok:false,error:"invalid_date"},400);const row=await byAd(env,date);if(!row)return null;if(path.endsWith("panchang"))return json({ok:true,date,bs:row.bs,nepal_sambat:row.ns,panchang:row.panchang,provenance:{source:source(row)==="r2"?"r2-backup":"patro-archive",version:env.CALENDAR_SOURCE_VERSION||"migrated"}},200,CACHE,source(row));return json({ok:true,date,...calendarShape(row),holidays:[]},200,CACHE,source(row))}
 if(path==="/api/v1/convert"){const ad=url.searchParams.get("ad"),bs=url.searchParams.get("bs");let row:any=null;if(ad){if(!validDate(ad))return json({ok:false,error:"invalid_ad"},400);row=await byAd(env,ad)}else if(bs){const m=bs.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(!m)return json({ok:false,error:"invalid_bs"},400);row=await byBs(env,Number(m[1]),Number(m[2]),Number(m[3]))}else return null;return row?json({ok:true,...calendarShape(row)},200,CACHE,source(row)):null}
 return null}
