import { TimeMachineAtlas } from "./time-machine/TimeMachineAtlas";
import { useEffect, useMemo, useState } from "react";
import { setPageTitle, toNepaliDigits } from "./title";

type AnyRecord=Record<string,any>;
const ON_THIS_DAY_REV="20261006-history-live-v4";
function todayNepal(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
async function getJson<T>(url:string,signal?:AbortSignal):Promise<T>{const response=await fetch(url,{headers:{accept:"application/json"},credentials:"same-origin",signal});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()}
function text(value:unknown,fallback="—"){const out=String(value??"").trim();return out||fallback}
function itemTitle(item:AnyRecord){return text(item.event_ne||item.title_ne||item.name_ne||item.headline_ne||item.title||item.name||item.event_en||item.event||item.headline,"ऐतिहासिक घटना")}
function itemBody(item:AnyRecord){return text(item.summary_ne||item.description_ne||item.detail_ne||item.summary||item.description||item.detail||item.details||item.body||item.event_en,"विवरण उपलब्ध छैन।")}
function itemYear(item:AnyRecord){const year=item.year_bs||item.bs_year||item.ad_year||item.year||item.date?.slice?.(0,4);return year?toNepaliDigits(year):""}
function itemMeta(item:AnyRecord){const parts=[] as string[];if(item.place)parts.push(String(item.place));if(item.category)parts.push(String(item.category));if(item.source_title)parts.push(String(item.source_title));return parts.join(" · ")}
function historySourceUrl(item:AnyRecord){const url=String(item.source_url||"").trim();return /^https?:\/\//i.test(url)?url:""}
function historyNeedsFurtherVerification(item:AnyRecord){return String(item.verification_status||"").trim().toLowerCase()==="unverified"||!historySourceUrl(item)}
function validMonthDay(value:string){if(!/^\d{2}-\d{2}$/.test(value))return false;const[month,day]=value.split("-").map(Number);if(month<1||month>12)return false;const max=new Date(Date.UTC(2000,month,0)).getUTCDate();return day>=1&&day<=max}
function adjacentMonthDay(value:string,delta:number){const[month,day]=value.split("-").map(Number);const date=new Date(Date.UTC(2000,month-1,day+delta));return `${String(date.getUTCMonth()+1).padStart(2,"0")}-${String(date.getUTCDate()).padStart(2,"0")}`}

export function TimeMachinePage(){
 const[data,setData]=useState<AnyRecord[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{setPageTitle("समययन्त्र")},[]);
 // Whole archive in one edge-cached request; the atlas filters by era/category/search on the client.
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");getJson<{items?:AnyRecord[]}>("/api/v1/time-machine?limit=800",controller.signal).then(payload=>setData(payload.items||[])).catch(()=>setError("ऐतिहासिक समयरेखा अहिले लोड हुन सकेन। केही बेरपछि फेरि प्रयास गर्नुहोस्।")).finally(()=>setLoading(false));return()=>controller.abort()},[]);
 return <TimeMachineAtlas items={data} loading={loading} error={error}/>;
}

export function OnThisDayPage({monthDay}:{monthDay?:string}={}){
 const archiveMonthDay=monthDay&&validMonthDay(monthDay)?monthDay:"";
 const[date,setDate]=useState(()=>archiveMonthDay?`2000-${archiveMonthDay}`:todayNepal()),[data,setData]=useState<AnyRecord[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[archiveTotal,setArchiveTotal]=useState(0);
 useEffect(()=>{setPageTitle(archiveMonthDay?`${archiveMonthDay} इतिहास अभिलेख`:"आज इतिहासमा")},[archiveMonthDay]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");if(archiveMonthDay){const[month,day]=archiveMonthDay.split("-");getJson<{days?:Record<string,AnyRecord[]>}>(`/data/on-this-day/month-${month}.json`,controller.signal).then(payload=>{const rows=payload.days?.[day]||[];setArchiveTotal(rows.length);setData(rows)}).catch(()=>setError("यो स्थायी इतिहास अभिलेख लोड हुन सकेन।")).finally(()=>setLoading(false))}else{getJson<{items?:AnyRecord[]}>(`/api/v1/on-this-day?date=${encodeURIComponent(date)}&rev=${ON_THIS_DAY_REV}`,controller.signal).then(payload=>setData(payload.items||[])).catch(()=>setError("यो मितिको इतिहास लोड हुन सकेन।")).finally(()=>setLoading(false))}return()=>controller.abort()},[archiveMonthDay,date]);
 if(monthDay&&!archiveMonthDay)return <main className="ap-page"><div className="ap-state ap-error">इतिहास अभिलेखको मिति मान्य छैन।</div></main>;
 if(archiveMonthDay){const prev=adjacentMonthDay(archiveMonthDay,-1),next=adjacentMonthDay(archiveMonthDay,1),sourceCount=data.filter(item=>Boolean(historySourceUrl(item))).length,needsCount=data.filter(historyNeedsFurtherVerification).length;return <main className="ap-page"><header className="ap-page-title"><span className="ap-eyebrow">स्थायी इतिहास अभिलेख</span><h1>{archiveMonthDay} — इतिहासमा</h1><p>यो स्थिर month/day archive हो। सबै अभिलेख देखाइन्छन्; स्रोत वा प्रमाणीकरण अपूर्ण भएका अभिलेखमा “Needs further verification / थप प्रमाणीकरण आवश्यक” भनेर स्पष्ट चिन्ह लगाइन्छ।</p></header><section className="ap-tool-section"><div className="ap-section-head"><div><h2>Archive records</h2><p>{archiveTotal} total · {sourceCount} source-cited · {needsCount} need further verification</p></div></div>{loading?<div className="ap-state">इतिहास लोड हुँदैछ…</div>:error?<div className="ap-state ap-error">{error}</div>:data.length?<div className="ap-history-list">{data.map((item,index)=>{const source=historySourceUrl(item),needsVerification=historyNeedsFurtherVerification(item);return <article className="ap-history-card" key={item.id||item.key||index}><div className="ap-history-year">{itemYear(item)}</div><div><h2>{itemTitle(item)}</h2>{itemMeta(item)&&<small>{itemMeta(item)}</small>}{needsVerification&&<p><strong data-verification="needs-further-verification">Needs further verification · थप प्रमाणीकरण आवश्यक</strong></p>}{source&&<p><a href={source} target="_blank" rel="nofollow noopener noreferrer">स्रोत हेर्नुहोस् ↗</a></p>}</div></article>})}</div>:<div className="ap-state">यो मितिका लागि अभिलेख हाल उपलब्ध छैन।</div>}<nav><a href={`/on-this-day/${prev}`}>← {prev}</a> · <a href="/on-this-day">आज इतिहासमा</a> · <a href={`/on-this-day/${next}`}>{next} →</a></nav><p><a href="/convert">मिति रूपान्तरण गर्नुहोस्</a></p></section></main>}
 return <main className="ap-page"><header className="ap-page-title"><span className="ap-eyebrow">इतिहास</span><h1>आज इतिहासमा</h1><p>चयन गरिएको मितिमा भएका अभिलेखित ऐतिहासिक घटना हेर्नुहोस्।</p></header><section className="ap-tool-section"><div className="ap-section-head"><div><h2>मिति अनुसार घटना</h2><p>{date}</p></div><label>मिति <input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label></div>{loading?<div className="ap-state">इतिहास लोड हुँदैछ…</div>:error?<div className="ap-state ap-error">{error}</div>:data.length?<div className="ap-history-list">{data.map((item,index)=><article className="ap-history-card" key={item.id||item.key||index}><div className="ap-history-year">{itemYear(item)}</div><div><h2>{itemTitle(item)}</h2>{itemMeta(item)&&<small>{itemMeta(item)}</small>}<p>{itemBody(item)}</p></div></article>)}</div>:<div className="ap-state">यो मितिका लागि अभिलेख भेटिएन।</div>}</section></main>
}

type DateView={ad:string;bs:any;ns:any;tithi:any;panchang:any};
function festivalDate(item:AnyRecord){return item.ad_date||item.fact_date||item.date||""}
function festivalName(item:AnyRecord){return text(item.name_ne||item.title_ne||item.label_ne||item.value?.label_ne||item.title||item.name_en||item.key,"चाडपर्व")}
function normalizeDate(payload:any,date:string):DateView{return {ad:payload?.calendars?.gregorian_ad||payload?.ad||payload?.date||date,bs:payload?.calendars?.bikram_sambat_detail||payload?.bs||{},ns:payload?.calendars?.nepal_sambat_detail||payload?.calendars?.nepal_sambat||payload?.nepal_sambat||{},tithi:payload?.tithi||payload?.panchang?.tithi||{},panchang:payload?.archive_panchang||payload?.panchang||{}}}
function bsText(bs:any,date:string){return bs?.formatted||[bs?.day&&toNepaliDigits(bs.day),bs?.month_ne,bs?.year&&toNepaliDigits(bs.year)].filter(Boolean).join(" ")||date}
function nsText(ns:any){if(typeof ns==="string")return ns;return ns?.formatted_ne||ns?.formatted||"नेपाल संवत्"}

export function DateDetailPage({date}:{date:string}){
 const[calendar,setCalendar]=useState<DateView|null>(null),[events,setEvents]=useState<AnyRecord[]>([]),[error,setError]=useState("");
 const valid=useMemo(()=>/^\d{4}-\d{2}-\d{2}$/.test(date),[date]);
 useEffect(()=>{setPageTitle(valid?`${date} को पात्रो`:"मिति")},[date,valid]);
 useEffect(()=>{if(!valid)return;const controller=new AbortController();setError("");(async()=>{try{let raw:any;try{raw=await getJson<any>(`/api/v1/sync?date=${encodeURIComponent(date)}`,controller.signal)}catch{raw=await getJson<any>(`/api/v1/today?date=${encodeURIComponent(date)}`,controller.signal)}setCalendar(normalizeDate(raw,date));const festivalPayload=await getJson<{items?:AnyRecord[]}>(`/api/v1/festivals?year=${date.slice(0,4)}`,controller.signal).catch(()=>({items:[]}));const holidayPayload=await getJson<{items?:AnyRecord[]}>(`/api/v1/holidays?date=${date}`,controller.signal).catch(()=>({items:[]}));const all=[...(festivalPayload.items||[]),...(holidayPayload.items||[])];const seen=new Set<string>();setEvents(all.filter(item=>{if(festivalDate(item)!==date)return false;const key=festivalName(item);if(seen.has(key))return false;seen.add(key);return true}))}catch{setError("मिति विवरण लोड हुन सकेन।")}})();return()=>controller.abort()},[date,valid]);
 if(!valid)return <main className="ap-page"><div className="ap-state ap-error">मिति मान्य छैन।</div></main>;
 if(error)return <main className="ap-page"><div className="ap-state ap-error">{error}</div></main>;
 if(!calendar)return <main className="ap-page"><div className="ap-state">मिति विवरण लोड हुँदैछ…</div></main>;
 const p=calendar.panchang||{};
 return <main className="ap-page"><header className="ap-page-title"><span className="ap-eyebrow">दैनिक पात्रो</span><h1>{bsText(calendar.bs,date)}</h1><p>{calendar.ad} · {nsText(calendar.ns)}</p></header><section className="ap-tool-section"><h2>पञ्चाङ्ग</h2><div className="ap-tool-grid"><div className="ap-tool-card"><span className="ap-tool-icon">ति</span><div><strong>{text(calendar.tithi?.ne||calendar.tithi?.name_ne||calendar.tithi?.tithi_name_ne||calendar.tithi?.name,"तिथि")}</strong><small>तिथि</small></div></div><div className="ap-tool-card"><span className="ap-tool-icon">सू</span><div><strong>{text(p.sunrise)}</strong><small>सूर्योदय</small></div></div><div className="ap-tool-card"><span className="ap-tool-icon">अ</span><div><strong>{text(p.sunset)}</strong><small>सूर्यास्त</small></div></div></div></section>{events.length>0&&<section className="ap-tool-section"><h2>चाडपर्व र बिदा</h2><div className="ap-news-grid">{events.map((item,index)=><article className="ap-news-card" key={item.id||index}><small>{text(item.effect||item.status,"पात्रो")}</small><h2>{festivalName(item)}</h2>{(item.description_ne||item.description)&&<p>{text(item.description_ne||item.description)}</p>}</article>)}</div></section>}<section className="ap-tool-section"><a href="/">← पात्रोमा फर्कनुहोस्</a></section></main>
}
