import { useEffect, useMemo, useState } from "react";
import { BS_MONTHS, calendarTitle, pageTitle, toNepaliDigits } from "./title";
import "./reference-home.css";

const NE_DAYS=["आइत","सोम","मंगल","बुध","बिही","शुक्र","शनि"];
const FULL_NE_DAYS=["आइतबार","सोमबार","मंगलबार","बुधबार","बिहीबार","शुक्रबार","शनिबार"];

type BsDate={year:number;month:number;day:number;month_ne?:string;formatted?:string};
type CalendarDay={ad:string;bs:BsDate;nepal_sambat?:any;panchang?:any};
type Festival={ad_date?:string;fact_date?:string;date?:string;name_ne?:string;title_ne?:string;label_ne?:string;name_en?:string;title?:string;key?:string;effect?:string;status?:string;description_ne?:string;value?:any};
type TodayView={ad:string;bs:BsDate|null;ns:string;tithi:string;tithiNext:string;sunrise:string;sunset:string};

function todayNepal(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
async function getJson<T>(url:string,signal?:AbortSignal):Promise<T>{const response=await fetch(url,{headers:{accept:"application/json"},signal,credentials:"same-origin"});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()}
function neDate(iso:string){return new Intl.DateTimeFormat("ne-NP",{timeZone:"Asia/Kathmandu",weekday:"long",year:"numeric",month:"long",day:"numeric"}).format(new Date(`${iso}T06:00:00Z`))}
function festivalDate(item:Festival){return item.ad_date||item.fact_date||item.date||""}
function festivalName(item:Festival){return item.name_ne||item.title_ne||item.label_ne||item.value?.label_ne||item.title||item.name_en||item.key||"चाडपर्व"}
function isHoliday(item:Festival){const text=`${item.effect||""} ${item.status||""} ${festivalName(item)}`.toLowerCase();return text.includes("holiday")||text.includes("बिदा")||text.includes("छुट्टी")}
function isoDay(date:Date){return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}-${String(date.getUTCDate()).padStart(2,"0")}`}
function previousDay(iso:string){const date=new Date(`${iso}T00:00:00Z`);date.setUTCDate(date.getUTCDate()-1);return isoDay(date)}
function daysUntil(from:string,to:string){return Math.max(0,Math.ceil((Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`))/86400000))}
function nsText(value:any){if(typeof value==="string")return value;if(!value)return "नेपाल संवत्";return value.formatted_ne||value.formatted||[value.year,value.month?.dev||value.month?.roman,value.tithi_name_ne].filter(Boolean).join(" ")||"नेपाल संवत्"}
function normalizeToday(payload:any,date:string):TodayView{const calendars=payload?.calendars;const bs:BsDate|null=calendars?.bikram_sambat_detail||payload?.bs||null;const p=payload?.archive_panchang||payload?.panchang||{};const t=payload?.tithi||p?.tithi||{};return{ad:calendars?.gregorian_ad||payload?.ad||payload?.date||date,bs,ns:nsText(calendars?.nepal_sambat_detail||calendars?.nepal_sambat||payload?.nepal_sambat),tithi:t?.ne||t?.name_ne||t?.tithi_name_ne||"तिथि",tithiNext:p?.tithi_transition?.time&&p?.tithi_transition?.next_ne?`${p.tithi_transition.time} देखि ${p.tithi_transition.next_ne}`:"आजको तिथि",sunrise:p?.sunrise||"—",sunset:p?.sunset||"—"}}
function normalizeDay(row:any):CalendarDay|null{if(row?.ad&&row?.bs)return{ad:String(row.ad),bs:row.bs,nepal_sambat:row.nepal_sambat||row.ns,panchang:row.panchang||{}};if(row?.calendars?.gregorian_ad&&row?.calendars?.bikram_sambat_detail)return{ad:row.calendars.gregorian_ad,bs:row.calendars.bikram_sambat_detail,nepal_sambat:row.calendars.nepal_sambat_detail||row.calendars.nepal_sambat,panchang:row.archive_panchang||{}};return null}
async function loadMonth(year:number,month:number,signal:AbortSignal){try{const primary=await getJson<any>(`/api/v1/calendar/${year}/${month}?calendar=bs`,signal);const rows=(primary?.days||[]).map(normalizeDay).filter(Boolean) as CalendarDay[];if(rows.length>=27)return rows}catch{}const nextYear=month===12?year+1:year,nextMonth=month===12?1:month+1;const[start,next]=await Promise.all([getJson<any>(`/api/v1/convert?bs=${year}-${String(month).padStart(2,"0")}-01`,signal),getJson<any>(`/api/v1/convert?bs=${nextYear}-${String(nextMonth).padStart(2,"0")}-01`,signal)]);if(!start?.ad||!next?.ad)throw new Error("month_anchor_unavailable");const range=await getJson<any>(`/api/v1/sync?start=${encodeURIComponent(start.ad)}&end=${encodeURIComponent(previousDay(next.ad))}`,signal);const rows=(range?.days||[]).map(normalizeDay).filter(Boolean) as CalendarDay[];return rows.filter(day=>day.bs.year===year&&day.bs.month===month)}
async function loadEvents(days:CalendarDay[],signal:AbortSignal){const years=[...new Set(days.map(day=>Number(day.ad.slice(0,4))).filter(Boolean))];const responses=await Promise.all(years.flatMap(year=>[getJson<{items?:Festival[]}>(`/api/v1/festivals?year=${year}`,signal).catch(()=>({items:[]})),getJson<{items?:Festival[]}>(`/api/v1/holidays?year=${year}`,signal).catch(()=>({items:[]}))]));const seen=new Set<string>();return responses.flatMap(row=>row.items||[]).filter(item=>{const key=`${festivalDate(item)}|${festivalName(item)}|${item.effect||""}`;if(!festivalDate(item)||seen.has(key))return false;seen.add(key);return true})}
function panchangTithi(day?:CalendarDay){return day?.panchang?.tithi?.ne||day?.panchang?.tithi_name_ne||day?.panchang?.tithi?.name_ne||"तिथि विवरण"}

function QuickActions(){return <div className="rh-actions" aria-label="मुख्य छिटो कार्य"><a href="/rashifal"><b>१२</b><span>आजको राशिफल</span></a><a href="/convert"><b>↔</b><span>मिति रूपान्तरण</span></a><a href="/me/reminders"><b>◷</b><span>तिथि रिमाइन्डर</span></a><a href="/me"><b>●</b><span>आफ्नै ठाउँ</span></a></div>}

function MonthCalendar({year,month,today,selected,onSelected,onLoaded}:{year:number;month:number;today:string;selected:string;onSelected:(iso:string)=>void;onLoaded:(days:CalendarDay[],events:Festival[])=>void}){
 const[days,setDays]=useState<CalendarDay[]>([]);const[events,setEvents]=useState<Festival[]>([]);const[error,setError]=useState("");const[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setDays([]);setEvents([]);setError("");loadMonth(year,month,controller.signal).then(async rows=>{const decorated=await loadEvents(rows,controller.signal);setDays(rows);setEvents(decorated);onLoaded(rows,decorated)}).catch(()=>setError("यो महिनाको पात्रो लोड हुन सकेन।"));return()=>controller.abort()},[year,month,retry,onLoaded]);
 const eventMap=useMemo(()=>{const map=new Map<string,Festival[]>();events.forEach(item=>{const date=festivalDate(item);const list=map.get(date)||[];list.push(item);map.set(date,list)});return map},[events]);
 const offset=days[0]?new Date(`${days[0].ad}T00:00:00Z`).getUTCDay():0;
 if(error)return <div className="rh-state rh-error"><p>{error}</p><button type="button" onClick={()=>setRetry(value=>value+1)}>फेरि प्रयास</button></div>;
 if(!days.length)return <div className="rh-state">पात्रो लोड हुँदैछ…</div>;
 return <><div className="rh-weekheads">{NE_DAYS.map((name,index)=><span className={index===6?"is-red":""} key={name}>{name}</span>)}</div><div className="rh-grid">{Array.from({length:offset}).map((_,index)=><span className="rh-cell is-empty" key={`empty-${index}`}/>)}{days.map(day=>{const weekday=new Date(`${day.ad}T00:00:00Z`).getUTCDay();const dayEvents=eventMap.get(day.ad)||[];const holiday=weekday===6||dayEvents.some(isHoliday);const festival=dayEvents.find(item=>!isHoliday(item))||dayEvents[0];return <button type="button" key={day.ad} onClick={()=>onSelected(day.ad)} className={`rh-cell${holiday?" is-holiday":""}${day.ad===today?" is-today":""}${day.ad===selected?" is-selected":""}`} aria-label={`${FULL_NE_DAYS[weekday]}, ${day.bs.day} ${BS_MONTHS[day.bs.month-1]} ${day.bs.year}`}><strong>{toNepaliDigits(day.bs.day)}</strong><small>{toNepaliDigits(new Date(`${day.ad}T00:00:00Z`).getUTCDate())}</small><em>{panchangTithi(day)}</em>{festival?<i>{festivalName(festival)}</i>:null}{holiday?<span className="rh-dot red" aria-hidden="true"/>:festival?<span className="rh-dot gold" aria-hidden="true"/>:null}</button>})}</div><div className="rh-legend"><span><i className="red"/> शनिबार / बिदा</span><span><i className="gold"/> चाडपर्व</span><span><i className="green"/> आज</span></div></>
}

export function ReferenceHomePage({calendarYear,calendarMonth}:{calendarYear?:number;calendarMonth?:number}){
 const today=todayNepal();const[todayData,setTodayData]=useState<TodayView|null>(null);const[todayError,setTodayError]=useState("");const[allEvents,setAllEvents]=useState<Festival[]>([]);const[cursor,setCursor]=useState<{year:number;month:number}|null>(calendarYear&&calendarMonth?{year:calendarYear,month:calendarMonth}:null);const[monthDays,setMonthDays]=useState<CalendarDay[]>([]);const[monthEvents,setMonthEvents]=useState<Festival[]>([]);const[selected,setSelected]=useState(today);
 useEffect(()=>{const controller=new AbortController();(async()=>{try{let raw:any;try{raw=await getJson<any>(`/api/v1/sync?date=${today}`,controller.signal)}catch{raw=await getJson<any>(`/api/v1/today?date=${today}`,controller.signal)}const view=normalizeToday(raw,today);setTodayData(view);if(!calendarYear&&!calendarMonth&&view.bs)setCursor({year:view.bs.year,month:view.bs.month})}catch{setTodayError("आजको पात्रो लोड हुन सकेन।")}})();const year=Number(today.slice(0,4));Promise.all([year,year+1].flatMap(y=>[getJson<{items?:Festival[]}>(`/api/v1/festivals?year=${y}`,controller.signal).catch(()=>({items:[]})),getJson<{items?:Festival[]}>(`/api/v1/holidays?year=${y}`,controller.signal).catch(()=>({items:[]}))])).then(rows=>setAllEvents(rows.flatMap(row=>row.items||[])));return()=>controller.abort()},[calendarYear,calendarMonth,today]);
 useEffect(()=>{document.title=calendarYear&&calendarMonth?calendarTitle(calendarYear,calendarMonth):pageTitle()},[calendarYear,calendarMonth]);
 const next=allEvents.filter(item=>festivalDate(item)>=today).sort((a,b)=>festivalDate(a).localeCompare(festivalDate(b)))[0];
 const selectedDay=monthDays.find(day=>day.ad===selected)||monthDays.find(day=>day.ad===today)||monthDays[0];
 const selectedEvents=monthEvents.filter(item=>festivalDate(item)===selectedDay?.ad);
 const upcoming=allEvents.filter(item=>festivalDate(item)>=today).sort((a,b)=>festivalDate(a).localeCompare(festivalDate(b))).slice(0,6);
 const visibleMonthEvents=monthEvents.slice().sort((a,b)=>festivalDate(a).localeCompare(festivalDate(b))).slice(0,10);
 const onLoaded=(days:CalendarDay[],events:Festival[])=>{setMonthDays(days);setMonthEvents(events);if(days.length&&!days.some(day=>day.ad===selected))setSelected(days.some(day=>day.ad===today)?today:days[0].ad)};
 const shift=(delta:number)=>setCursor(current=>{if(!current)return current;let year=current.year,month=current.month+delta;if(month<1){month=12;year--}if(month>12){month=1;year++}history.pushState(null,"",`/calendar/${year}/${String(month).padStart(2,"0")}`);window.dispatchEvent(new Event("patro:navigation"));return{year,month}});
 const bs=todayData?.bs;
 return <main className="rh-page">
  <section className="rh-band" aria-labelledby="rh-today-title">
   <article className="rh-today"><span className="rh-kicker">आज · {neDate(today).split(",")[0]}</span><h1 id="rh-today-title">{bs?`${toNepaliDigits(bs.day)} ${bs.month_ne||BS_MONTHS[bs.month-1]} ${toNepaliDigits(bs.year)}`:"आजको नेपाली पात्रो"}</h1><p>{neDate(today)} · {toNepaliDigits(today)}</p>{todayError?<small className="rh-inline-error">{todayError}</small>:null}<div className="rh-facts"><div><span>तिथि</span><b>{todayData?.tithi||"—"}</b><small>{todayData?.tithiNext||""}</small></div><div><span>नेपाल संवत्</span><b>{todayData?.ns||"—"}</b></div><div><span>सूर्योदय · सूर्यास्त</span><b>{todayData?.sunrise||"—"} · {todayData?.sunset||"—"}</b></div></div></article>
   <article className="rh-next"><span className="rh-kicker">आउँदो चाडपर्व</span>{next?<><h2>{festivalName(next)}</h2><p>{neDate(festivalDate(next))}</p><strong>{toNepaliDigits(daysUntil(today,festivalDate(next)))} दिन बाँकी</strong><a href={`/date/${festivalDate(next)}`}>पूरा विवरण →</a></>:<><h2>चाडपर्व पात्रो</h2><p>यो महिनाका चाडपर्व र सार्वजनिक बिदा हेर्नुहोस्।</p></>}<QuickActions/></article>
  </section>
  <div className="rh-layout">
   <div className="rh-main-stack">
    <section className="rh-card rh-calendar"><header className="rh-card-head"><div><span className="rh-kicker">नेपाली पात्रो</span><h2>{cursor?`${BS_MONTHS[cursor.month-1]} ${toNepaliDigits(cursor.year)}`:"यो महिना"}</h2><p>तिथि, चाडपर्व र सार्वजनिक बिदासहित</p></div><div className="rh-month-actions"><button type="button" onClick={()=>shift(-1)} aria-label="अघिल्लो महिना">‹</button><a href="/">आज</a><button type="button" onClick={()=>shift(1)} aria-label="अर्को महिना">›</button></div></header>{cursor?<MonthCalendar year={cursor.year} month={cursor.month} today={today} selected={selected} onSelected={setSelected} onLoaded={onLoaded}/>:<div className="rh-state">आजको पात्रो तयार हुँदैछ…</div>}</section>
    <section className="rh-card rh-selected" aria-live="polite"><header className="rh-card-head"><div><span className="rh-kicker">छानिएको दिन</span><h2>{selectedDay?`${toNepaliDigits(selectedDay.bs.day)} ${BS_MONTHS[selectedDay.bs.month-1]} ${toNepaliDigits(selectedDay.bs.year)}`:"दिन छान्नुहोस्"}</h2><p>{selectedDay?neDate(selectedDay.ad):"पात्रोबाट कुनै दिन छान्नुहोस्।"}</p></div>{selectedDay?<a className="rh-link" href={`/date/${selectedDay.ad}`}>पूरा दिन विवरण →</a>:null}</header>{selectedDay?<div className="rh-selected-grid"><div><span>तिथि</span><b>{panchangTithi(selectedDay)}</b></div><div><span>नेपाल संवत्</span><b>{nsText(selectedDay.nepal_sambat)}</b></div><div><span>AD</span><b>{selectedDay.ad}</b></div><div><span>चाडपर्व / बिदा</span><b>{selectedEvents.length?selectedEvents.map(festivalName).join(" · "):"सामान्य दिन"}</b></div></div>:null}</section>
    <section className="rh-card"><header className="rh-card-head"><div><span className="rh-kicker">यो महिनाका मुख्य दिन</span><h2>चाडपर्व र बिदा</h2></div></header><div className="rh-event-list">{visibleMonthEvents.length?visibleMonthEvents.map((item,index)=><a href={`/date/${festivalDate(item)}`} key={`${festivalDate(item)}-${index}`}><time>{neDate(festivalDate(item)).replace(/,.*/,"")}</time><strong>{festivalName(item)}</strong><span className={isHoliday(item)?"is-holiday":""}>{isHoliday(item)?"सार्वजनिक बिदा":"चाडपर्व"}</span></a>):<p className="rh-muted">यो महिनाको कार्यक्रम सूची लोड भएपछि यहाँ देखिन्छ।</p>}</div></section>
    <section className="rh-card rh-faq"><header className="rh-card-head"><div><span className="rh-kicker">सहयोग</span><h2>प्रायः सोधिने प्रश्न</h2></div></header><details><summary>आज कति गते हो?</summary><p>माथिको “आज” कार्डमा काठमाडौं समयअनुसार आजको वि.सं. मिति, तिथि, नेपाल संवत्, सूर्योदय र सूर्यास्त देखिन्छ।</p></details><details><summary>वि.सं. र ई.सं. कसरी रूपान्तरण गर्ने?</summary><p><a href="/convert">मिति रूपान्तरण</a> खोल्नुहोस्। एउटै उपकरणबाट BS ↔ AD दुवैतर्फ रूपान्तरण गर्न सकिन्छ।</p></details><details><summary>खगोलीय पात्रो कहाँ छ?</summary><p><a href="/tools/astro">खगोलीय पात्रो</a> छुट्टै उपकरणका रूपमा उपलब्ध छ; मुख्य पृष्ठ नेपाली पात्रो र आजको दिनका लागि केन्द्रित छ।</p></details></section>
    <section className="rh-card rh-seo-copy"><h2>नेपाली पात्रो, तपाईंकै लागि</h2><p>आफ्नै पात्रोमा नेपाली मिति, तिथि, नेपाल संवत्, चाडपर्व, सार्वजनिक बिदा र दैनिक पञ्चाङ्ग एउटै स्पष्ट अनुभवमा राखिएको छ। मिति रूपान्तरण, नेपाली टाइपिङ, राशिफल, समययन्त्र, समुदाय पात्रो, रेडियो, टिभी र अन्य उपयोगी उपकरण मुख्य पात्रोसँग जोडिएका छन्।</p></section>
   </div>
   <aside className="rh-side" aria-label="पात्रो सहायक सामग्री">
    <section className="rh-card"><header className="rh-card-head"><div><span className="rh-kicker">आगामी</span><h2>नजिकका चाडपर्व</h2></div></header><div className="rh-upcoming">{upcoming.length?upcoming.map((item,index)=><a href={`/date/${festivalDate(item)}`} key={`${festivalDate(item)}-${index}`}><strong>{festivalName(item)}</strong><small>{neDate(festivalDate(item))}</small></a>):<p className="rh-muted">आगामी चाडपर्व लोड हुँदैछन्…</p>}</div></section>
    <section className="rh-card"><header className="rh-card-head"><div><span className="rh-kicker">छिटो पहुँच</span><h2>दैनिक प्रयोग</h2></div></header><div className="rh-quick-grid"><a href="/rashifal"><b>♈</b><span>राशिफल</span></a><a href="/convert"><b>↔</b><span>मिति रूपान्तरण</span></a><a href="/tools/nepali-typing"><b>ने</b><span>नेपाली टाइपिङ</span></a><a href="/tools/voice-typing"><b>🎙</b><span>Voice to Text</span></a><a href="/time-machine"><b>⌛</b><span>समययन्त्र</span></a><a href="/on-this-day"><b>इत</b><span>आज इतिहासमा</span></a><a href="/samudaya"><b>◎</b><span>समुदाय पात्रो</span></a><a href="/tools/astro"><b>☾</b><span>खगोलीय पात्रो</span></a></div></section>
    <a className="rh-astro-teaser" href="/tools/astro"><span>खगोलीय पात्रो</span><strong>चन्द्र अवस्था, तिथि र आकाशीय घटना</strong><small>मुख्य पात्रोबाट अलग पूर्ण खगोलीय अनुभव खोल्नुहोस् →</small></a>
   </aside>
  </div>
 </main>
}
