import { useCallback, useEffect, useMemo, useState } from "react";
import { adToBs, bsToAd, daysInBsMonth } from "../packages/core/src";
import { BS_MONTHS, calendarTitle, pageTitle, toNepaliDigits } from "./title";
import "./reference-home.css";

const NE_DAYS=["आइत","सोम","मंगल","बुध","बिही","शुक्र","शनि"];
const FULL_NE_DAYS=["आइतबार","सोमबार","मंगलबार","बुधबार","बिहीबार","शुक्रबार","शनिबार"];

type BsDate={year:number;month:number;day:number;month_ne?:string;formatted?:string};
type CalendarDay={ad:string;bs:BsDate;nepal_sambat?:any;panchang?:any};
type Festival={ad_date?:string;fact_date?:string;date?:string;name_ne?:string;title_ne?:string;label_ne?:string;name_en?:string;title?:string;key?:string;effect?:string;status?:string;description_ne?:string;value?:any};
type TodayView={ad:string;bs:BsDate|null;ns:string;tithi:string;tithiNext:string;sunrise:string;sunset:string};
type WeatherDay={date:string;code:number;tmax?:number;tmin?:number};

function todayNepal(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kathmandu",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
async function getJson<T>(url:string,signal?:AbortSignal):Promise<T>{const response=await fetch(url,{headers:{accept:"application/json"},signal,credentials:"same-origin"});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json()}
function neDate(iso:string,withWeekday=true){return new Intl.DateTimeFormat("ne-NP",{timeZone:"Asia/Kathmandu",...(withWeekday?{weekday:"long"}:{}) ,year:"numeric",month:"long",day:"numeric"}).format(new Date(`${iso}T06:00:00Z`))}
function festivalDate(item:Festival){return item.ad_date||item.fact_date||item.date||""}
function festivalName(item:Festival){return item.name_ne||item.title_ne||item.label_ne||item.value?.label_ne||item.title||item.name_en||item.key||"चाडपर्व"}
function isHoliday(item:Festival){const text=`${item.effect||""} ${item.status||""} ${festivalName(item)}`.toLowerCase();return text.includes("holiday")||text.includes("बिदा")||text.includes("छुट्टी")}
function isoDay(date:Date){return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}-${String(date.getUTCDate()).padStart(2,"0")}`}
function previousDay(iso:string){const date=new Date(`${iso}T00:00:00Z`);date.setUTCDate(date.getUTCDate()-1);return isoDay(date)}
function daysUntil(from:string,to:string){return Math.max(0,Math.ceil((Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`))/86400000))}
function nsText(value:any){if(typeof value==="string")return value;if(!value)return "";return value.formatted_ne||value.formatted||[value.year,value.month?.dev||value.month?.roman,value.tithi_name_ne||value.day].filter(Boolean).join(" ")||""}
function nsCellText(value:any){
 if(!value)return "";
 if(typeof value==="object"){
  const month=value.month?.dev||value.month?.ne||value.month_ne||value.month_name_ne||"";
  const day=value.day??value.tithi_day??value.date_day??value.tithi?.day;
  if(day!==undefined&&day!==null)return `नेसं ${month?`${month} `:""}${toNepaliDigits(day)}`.trim();
  const year=value.year??value.ns_year;
  if(year)return `नेसं ${toNepaliDigits(year)}`;
 }
 const text=nsText(value).replace(/^नेपाल\s*संवत्\s*/i,"").trim();
 return text?`नेसं ${text.split(/\s+/).slice(-2).join(" ")}`:"";
}
function decorateBs(value:{year:number;month:number;day:number}):BsDate{return{...value,month_ne:BS_MONTHS[value.month-1],formatted:`${toNepaliDigits(value.day)} ${BS_MONTHS[value.month-1]} ${toNepaliDigits(value.year)}`}}
function localToday(date:string):TodayView{try{return{ad:date,bs:decorateBs(adToBs(date)),ns:"",tithi:"",tithiNext:"",sunrise:"",sunset:""}}catch{return{ad:date,bs:null,ns:"",tithi:"",tithiNext:"",sunrise:"",sunset:""}}}
function normalizeToday(payload:any,date:string,fallback:TodayView):TodayView{const calendars=payload?.calendars;const rawBs=calendars?.bikram_sambat_detail||payload?.bs||fallback.bs;const bs=rawBs?{...rawBs,month_ne:rawBs.month_ne||BS_MONTHS[rawBs.month-1]}:fallback.bs;const p=payload?.archive_panchang||payload?.panchang||{};const t=payload?.tithi||p?.tithi||{};return{ad:calendars?.gregorian_ad||payload?.ad||payload?.date||date,bs,ns:nsText(calendars?.nepal_sambat_detail||calendars?.nepal_sambat||payload?.nepal_sambat)||fallback.ns,tithi:t?.ne||t?.name_ne||t?.tithi_name_ne||fallback.tithi,tithiNext:p?.tithi_transition?.time&&p?.tithi_transition?.next_ne?`${p.tithi_transition.time} देखि ${p.tithi_transition.next_ne}`:fallback.tithiNext,sunrise:p?.sunrise||fallback.sunrise,sunset:p?.sunset||fallback.sunset}}
function normalizeDay(row:any):CalendarDay|null{if(row?.ad&&row?.bs)return{ad:String(row.ad),bs:{...row.bs,month_ne:row.bs.month_ne||BS_MONTHS[row.bs.month-1]},nepal_sambat:row.nepal_sambat||row.ns,panchang:row.panchang||{}};if(row?.calendars?.gregorian_ad&&row?.calendars?.bikram_sambat_detail){const bs=row.calendars.bikram_sambat_detail;return{ad:row.calendars.gregorian_ad,bs:{...bs,month_ne:bs.month_ne||BS_MONTHS[bs.month-1]},nepal_sambat:row.calendars.nepal_sambat_detail||row.calendars.nepal_sambat,panchang:row.archive_panchang||{}}}return null}
function localMonthDays(year:number,month:number):CalendarDay[]{try{const total=daysInBsMonth(year,month);return Array.from({length:total},(_,index)=>{const day=index+1;return{ad:bsToAd({year,month,day}),bs:decorateBs({year,month,day}),panchang:{}}})}catch{return[]}}
function mergeDays(local:CalendarDay[],remote:CalendarDay[]){if(!remote.length)return local;const byAd=new Map(remote.map(day=>[day.ad,day]));return local.map(day=>{const richer=byAd.get(day.ad);return richer?{...day,...richer,bs:{...day.bs,...richer.bs}}:day})}
async function loadMonth(year:number,month:number,signal:AbortSignal){const fallback=localMonthDays(year,month);try{const primary=await getJson<any>(`/api/v1/calendar/${year}/${month}?calendar=bs`,signal);const rows=(primary?.days||[]).map(normalizeDay).filter(Boolean) as CalendarDay[];if(rows.length>=27)return mergeDays(fallback,rows)}catch{}try{const start=bsToAd({year,month,day:1});const nextYear=month===12?year+1:year,nextMonth=month===12?1:month+1;const next=bsToAd({year:nextYear,month:nextMonth,day:1});const range=await getJson<any>(`/api/v1/sync?start=${encodeURIComponent(start)}&end=${encodeURIComponent(previousDay(next))}`,signal);const rows=(range?.days||[]).map(normalizeDay).filter(Boolean) as CalendarDay[];return mergeDays(fallback,rows.filter(day=>day.bs.year===year&&day.bs.month===month))}catch{return fallback}}
async function loadEvents(days:CalendarDay[],signal:AbortSignal){const years=[...new Set(days.map(day=>Number(day.ad.slice(0,4))).filter(Boolean))];const responses=await Promise.all(years.flatMap(year=>[getJson<{items?:Festival[]}>(`/api/v1/festivals?year=${year}`,signal).catch(()=>({items:[]})),getJson<{items?:Festival[]}>(`/api/v1/holidays?year=${year}`,signal).catch(()=>({items:[]}))]));const seen=new Set<string>();return responses.flatMap(row=>row.items||[]).filter(item=>{const key=`${festivalDate(item)}|${festivalName(item)}|${item.effect||""}`;if(!festivalDate(item)||seen.has(key))return false;seen.add(key);return true})}
function panchangTithi(day?:CalendarDay){return day?.panchang?.tithi?.ne||day?.panchang?.tithi_name_ne||day?.panchang?.tithi?.name_ne||""}
function weatherIcon(code:number){if(code===0)return"☀";if(code===1||code===2)return"🌤";if(code===3)return"☁";if(code===45||code===48)return"🌫";if((code>=51&&code<=67)||(code>=80&&code<=82))return"🌧";if((code>=71&&code<=77)||(code>=85&&code<=86))return"❄";if(code>=95)return"⛈";return"☁"}
function monthSubtitle(days:CalendarDay[]){if(!days.length)return"तिथि · चाडपर्व · बिदा · काठमाडौं मौसम";const format=new Intl.DateTimeFormat("ne-NP",{timeZone:"Asia/Kathmandu",month:"long",year:"numeric"});const first=format.format(new Date(`${days[0].ad}T06:00:00Z`));const last=format.format(new Date(`${days[days.length-1].ad}T06:00:00Z`));return `${first===last?first:`${first} – ${last}`} · ${toNepaliDigits(days.length)} दिन`}
async function loadKathmanduWeather(signal:AbortSignal):Promise<WeatherDay[]>{
 const url=new URL("https://api.open-meteo.com/v1/forecast");
 url.searchParams.set("latitude","27.7172");url.searchParams.set("longitude","85.3240");url.searchParams.set("daily","weather_code,temperature_2m_max,temperature_2m_min");url.searchParams.set("timezone","Asia/Kathmandu");url.searchParams.set("forecast_days","14");url.searchParams.set("past_days","1");
 try{const response=await fetch(url.toString(),{signal,headers:{accept:"application/json"},credentials:"omit"});if(!response.ok)return[];const body:any=await response.json();const times=Array.isArray(body?.daily?.time)?body.daily.time:[];return times.map((date:string,index:number)=>({date,code:Number(body.daily.weather_code?.[index]??-1),tmax:Number(body.daily.temperature_2m_max?.[index]),tmin:Number(body.daily.temperature_2m_min?.[index])})).filter((row:WeatherDay)=>/^\d{4}-\d{2}-\d{2}$/.test(row.date)&&row.code>=0)}catch{return[]}
}

function QuickActions(){return <div className="rh-actions" aria-label="मुख्य छिटो कार्य"><a href="/rashifal"><b>१२</b><span>आजको राशिफल</span></a><a href="/convert"><b>↔</b><span>मिति रूपान्तरण</span></a><a href="/me/reminders"><b>◷</b><span>तिथि रिमाइन्डर</span></a><a href="/me"><b>●</b><span>आफ्नै ठाउँ</span></a></div>}

function MonthCalendar({year,month,today,selected,onSelected,onLoaded,weather}:{year:number;month:number;today:string;selected:string;onSelected:(iso:string)=>void;onLoaded:(days:CalendarDay[],events:Festival[])=>void;weather:Map<string,WeatherDay>}){
 const localDays=useMemo(()=>localMonthDays(year,month),[year,month]);
 const[days,setDays]=useState<CalendarDay[]>(localDays);const[events,setEvents]=useState<Festival[]>([]);
 useEffect(()=>{let active=true;const controller=new AbortController();setDays(localDays);setEvents([]);onLoaded(localDays,[]);(async()=>{const rows=await loadMonth(year,month,controller.signal);const decorated=await loadEvents(rows,controller.signal);if(!active)return;setDays(rows);setEvents(decorated);onLoaded(rows,decorated)})().catch(()=>{});return()=>{active=false;controller.abort()}},[year,month,localDays,onLoaded]);
 const eventMap=useMemo(()=>{const map=new Map<string,Festival[]>();events.forEach(item=>{const date=festivalDate(item);const list=map.get(date)||[];list.push(item);map.set(date,list)});return map},[events]);
 const offset=days[0]?new Date(`${days[0].ad}T00:00:00Z`).getUTCDay():0;
 if(!days.length)return <div className="rh-state">यो महिनाको पात्रो उपलब्ध छैन।</div>;
 return <><div className="rh-weekheads">{NE_DAYS.map((name,index)=><span className={index===6?"is-red":""} key={name}>{name}</span>)}</div><div className="rh-grid">{Array.from({length:offset}).map((_,index)=><span className="rh-cell is-empty" key={`empty-${index}`}/>)}{days.map(day=>{const weekday=new Date(`${day.ad}T00:00:00Z`).getUTCDay();const dayEvents=eventMap.get(day.ad)||[];const holiday=weekday===6||dayEvents.some(isHoliday);const tithi=panchangTithi(day);const forecast=weather.get(day.ad);const labels=dayEvents.slice(0,2);const ns=nsCellText(day.nepal_sambat);const fullNs=nsText(day.nepal_sambat);return <button type="button" key={day.ad} onClick={()=>onSelected(day.ad)} className={`rh-cell${holiday?" is-holiday":""}${day.ad===today?" is-today":""}${day.ad===selected?" is-selected":""}`} aria-label={`${FULL_NE_DAYS[weekday]}, ${day.bs.day} ${BS_MONTHS[day.bs.month-1]} ${day.bs.year}${tithi?`, ${tithi}`:""}${labels.length?`, ${labels.map(festivalName).join(", ")}`:""}`}><span className="rh-cell-top"><span className="rh-ad-date" title={`ई.सं. ${day.ad}`}>{toNepaliDigits(new Date(`${day.ad}T00:00:00Z`).getUTCDate())}</span><span className="rh-ns-date" title={fullNs||"नेपाल संवत् विवरण उपलब्ध हुँदा देखिन्छ"}>{ns}</span></span><span className="rh-cell-main"><strong>{toNepaliDigits(day.bs.day)}</strong>{forecast?<span className="rh-weather" title={`काठमाडौं पूर्वानुमान: ${Math.round(forecast.tmin??0)}°–${Math.round(forecast.tmax??0)}°C`}>{weatherIcon(forecast.code)}</span>:null}</span><span className="rh-weekday">{NE_DAYS[weekday]}</span><em className={tithi?"":"is-pending"}>{tithi}</em><span className="rh-day-badges">{labels.map((item,index)=><span key={`${festivalName(item)}-${index}`} className={isHoliday(item)?"is-holiday-badge":"is-festival-badge"}>{festivalName(item)}</span>)}{weekday===6&&!dayEvents.some(isHoliday)?<span className="is-holiday-badge">शनिबार</span>:null}</span></button>})}</div><div className="rh-legend"><span><i className="red"/> शनिबार / बिदा</span><span><i className="gold"/> चाडपर्व</span><span><i className="green"/> आज</span><span>☀ काठमाडौं मौसम</span></div></>
}

export function ReferenceHomePage({calendarYear,calendarMonth}:{calendarYear?:number;calendarMonth?:number}){
 const today=todayNepal();
 const local=useMemo(()=>localToday(today),[today]);
 const[todayData,setTodayData]=useState<TodayView>(local);
 const[allEvents,setAllEvents]=useState<Festival[]>([]);
 const[weatherDays,setWeatherDays]=useState<WeatherDay[]>([]);
 const[cursor,setCursor]=useState<{year:number;month:number}|null>(()=>calendarYear&&calendarMonth?{year:calendarYear,month:calendarMonth}:local.bs?{year:local.bs.year,month:local.bs.month}:null);
 const[monthDays,setMonthDays]=useState<CalendarDay[]>(()=>cursor?localMonthDays(cursor.year,cursor.month):[]);
 const[monthEvents,setMonthEvents]=useState<Festival[]>([]);
 const[selected,setSelected]=useState(today);
 const weatherByDate=useMemo(()=>new Map(weatherDays.map(day=>[day.date,day])),[weatherDays]);
 useEffect(()=>{if(calendarYear&&calendarMonth)setCursor({year:calendarYear,month:calendarMonth})},[calendarYear,calendarMonth]);
 useEffect(()=>{const controller=new AbortController();setTodayData(local);(async()=>{try{let raw:any;try{raw=await getJson<any>(`/api/v1/sync?date=${today}`,controller.signal)}catch{raw=await getJson<any>(`/api/v1/today?date=${today}`,controller.signal)}setTodayData(normalizeToday(raw,today,local))}catch{}})();const year=Number(today.slice(0,4));Promise.all([year,year+1].flatMap(y=>[getJson<{items?:Festival[]}>(`/api/v1/festivals?year=${y}`,controller.signal).catch(()=>({items:[]})),getJson<{items?:Festival[]}>(`/api/v1/holidays?year=${y}`,controller.signal).catch(()=>({items:[]}))])).then(rows=>setAllEvents(rows.flatMap(row=>row.items||[]))).catch(()=>{});loadKathmanduWeather(controller.signal).then(setWeatherDays).catch(()=>{});return()=>controller.abort()},[local,today]);
 useEffect(()=>{document.title=calendarYear&&calendarMonth?calendarTitle(calendarYear,calendarMonth):pageTitle()},[calendarYear,calendarMonth]);
 const next=allEvents.filter(item=>festivalDate(item)>=today).sort((a,b)=>festivalDate(a).localeCompare(festivalDate(b)))[0];
 const selectedDay=monthDays.find(day=>day.ad===selected)||monthDays.find(day=>day.ad===today)||monthDays[0];
 const selectedEvents=monthEvents.filter(item=>festivalDate(item)===selectedDay?.ad);
 const upcoming=allEvents.filter(item=>festivalDate(item)>=today).sort((a,b)=>festivalDate(a).localeCompare(festivalDate(b))).slice(0,6);
 const visibleMonthEvents=monthEvents.slice().sort((a,b)=>festivalDate(a).localeCompare(festivalDate(b))).slice(0,10);
 const onLoaded=useCallback((days:CalendarDay[],events:Festival[])=>{setMonthDays(days);setMonthEvents(events);setSelected(current=>days.some(day=>day.ad===current)?current:days.some(day=>day.ad===today)?today:days[0]?.ad||current)},[today]);
 const shift=(delta:number)=>setCursor(current=>{if(!current)return current;let year=current.year,month=current.month+delta;if(month<1){month=12;year--}if(month>12){month=1;year++}history.pushState(null,"",`/calendar/${year}/${String(month).padStart(2,"0")}`);window.dispatchEvent(new Event("patro:navigation"));return{year,month}});
 const bs=todayData.bs||local.bs;
 const tithiLine=todayData.tithi?`${todayData.tithi}${todayData.tithiNext?` · ${todayData.tithiNext}`:""}`:`${FULL_NE_DAYS[new Date(`${today}T00:00:00Z`).getUTCDay()]} · नेपाली मिति`;
 return <main className="rh-page">
  <section className="rh-band" aria-labelledby="rh-today-title">
   <article className="rh-today"><span className="rh-kicker">आज · {neDate(today).split(",")[0]}</span><h1 id="rh-today-title">{bs?`${toNepaliDigits(bs.day)} ${bs.month_ne||BS_MONTHS[bs.month-1]} ${toNepaliDigits(bs.year)}`:"आजको नेपाली पात्रो"}</h1><p className="rh-tithi-line">{tithiLine}</p><div className="rh-facts"><div><span>अङ्ग्रेजी मिति</span><b>{neDate(today,false)}</b><small>{today}</small></div><div><span>नेपाल संवत्</span><b>{todayData.ns||"—"}</b>{todayData.ns?<small>नेपाल संवत्</small>:null}</div><div><span>सूर्योदय · सूर्यास्त</span><b>{todayData.sunrise&&todayData.sunset?`${todayData.sunrise} · ${todayData.sunset}`:"—"}</b>{todayData.sunrise&&todayData.sunset?<small>काठमाडौं समय</small>:null}</div></div></article>
   <article className="rh-next"><span className="rh-kicker">आउँदो चाडपर्व</span>{next?<><h2>{festivalName(next)}</h2><p>{neDate(festivalDate(next))}</p><strong>{toNepaliDigits(daysUntil(today,festivalDate(next)))} दिन बाँकी</strong><a href={`/date/${festivalDate(next)}`}>पूरा विवरण →</a></>:<><h2>चाडपर्व र बिदा</h2><p>नजिकको चाडपर्व विवरण अहिले उपलब्ध छैन।</p></>}<QuickActions/></article>
  </section>
  <div className="rh-layout">
   <div className="rh-main-stack">
    <section className="rh-card rh-calendar"><header className="rh-card-head"><div><span className="rh-kicker">नेपाली पात्रो</span><h2>{cursor?`${BS_MONTHS[cursor.month-1]} ${toNepaliDigits(cursor.year)}`:"यो महिना"}</h2><p>{monthSubtitle(monthDays)}</p></div><div className="rh-month-actions"><button type="button" onClick={()=>shift(-1)} aria-label="अघिल्लो महिना">‹</button><a href="/">आज</a><button type="button" onClick={()=>shift(1)} aria-label="अर्को महिना">›</button></div></header>{cursor?<MonthCalendar year={cursor.year} month={cursor.month} today={today} selected={selected} onSelected={setSelected} onLoaded={onLoaded} weather={weatherByDate}/>:<div className="rh-state">यो महिनाको पात्रो उपलब्ध छैन।</div>}</section>
    <section className="rh-card rh-selected" aria-live="polite"><header className="rh-card-head"><div><span className="rh-kicker">छानिएको दिन</span><h2>{selectedDay?`${toNepaliDigits(selectedDay.bs.day)} ${BS_MONTHS[selectedDay.bs.month-1]} ${toNepaliDigits(selectedDay.bs.year)}`:"दिन छान्नुहोस्"}</h2><p>{selectedDay?neDate(selectedDay.ad):"पात्रोबाट कुनै दिन छान्नुहोस्।"}</p></div>{selectedDay?<a className="rh-link" href={`/date/${selectedDay.ad}`}>पूरा दिन विवरण →</a>:null}</header>{selectedDay?<div className="rh-selected-grid"><div><span>तिथि</span><b>{panchangTithi(selectedDay)||"—"}</b></div><div><span>नेपाल संवत्</span><b>{nsText(selectedDay.nepal_sambat)||"—"}</b></div><div><span>ई.सं.</span><b>{selectedDay.ad}</b></div><div><span>चाडपर्व / बिदा</span><b>{selectedEvents.length?selectedEvents.map(festivalName).join(" · "):"कुनै सूचीबद्ध कार्यक्रम छैन"}</b></div></div>:null}</section>
    <section className="rh-card"><header className="rh-card-head"><div><span className="rh-kicker">यो महिनाका मुख्य दिन</span><h2>चाडपर्व र बिदा</h2></div></header><div className="rh-event-list">{visibleMonthEvents.length?visibleMonthEvents.map((item,index)=><a href={`/date/${festivalDate(item)}`} key={`${festivalDate(item)}-${index}`}><time>{neDate(festivalDate(item)).replace(/,.*/,"")}</time><strong>{festivalName(item)}</strong><span className={isHoliday(item)?"is-holiday":""}>{isHoliday(item)?"सार्वजनिक बिदा":"चाडपर्व"}</span></a>):<p className="rh-muted">यस महिनाका थप चाडपर्व वा बिदा विवरण उपलब्ध छैनन्।</p>}</div></section>
    <section className="rh-card rh-faq"><header className="rh-card-head"><div><span className="rh-kicker">सहयोग</span><h2>प्रायः सोधिने प्रश्न</h2></div></header><details><summary>आज कति गते हो?</summary><p>माथिको “आज” कार्डमा काठमाडौं समयअनुसार आजको वि.सं. मिति तुरुन्त देखिन्छ। उपलब्ध हुँदा तिथि, नेपाल संवत्, सूर्योदय र सूर्यास्त पनि थपिन्छ।</p></details><details><summary>वि.सं. र ई.सं. कसरी रूपान्तरण गर्ने?</summary><p><a href="/convert">मिति रूपान्तरण</a> खोल्नुहोस्। एउटै उपकरणबाट BS ↔ AD दुवैतर्फ रूपान्तरण गर्न सकिन्छ, अफलाइनमा पनि।</p></details><details><summary>खगोलीय पात्रो कहाँ छ?</summary><p><a href="/tools/astro">खगोलीय पात्रो</a> छुट्टै उपकरणका रूपमा उपलब्ध छ; मुख्य पृष्ठ नेपाली पात्रो र आजको दिनका लागि केन्द्रित छ।</p></details></section>
    <section className="rh-card rh-seo-copy"><h2>नेपाली पात्रो, तपाईंकै लागि</h2><p>आफ्नै पात्रोमा नेपाली मिति, तिथि, नेपाल संवत्, चाडपर्व, सार्वजनिक बिदा र दैनिक पञ्चाङ्ग एउटै स्पष्ट अनुभवमा राखिएको छ। मिति रूपान्तरण, नेपाली टाइपिङ, राशिफल, समययन्त्र, समुदाय पात्रो, रेडियो, टिभी र अन्य उपयोगी उपकरण मुख्य पात्रोसँग जोडिएका छन्।</p></section>
   </div>
   <aside className="rh-side" aria-label="पात्रो सहायक सामग्री">
    <section className="rh-card"><header className="rh-card-head"><div><span className="rh-kicker">आगामी</span><h2>नजिकका चाडपर्व</h2></div></header><div className="rh-upcoming">{upcoming.length?upcoming.map((item,index)=><a href={`/date/${festivalDate(item)}`} key={`${festivalDate(item)}-${index}`}><strong>{festivalName(item)}</strong><small>{neDate(festivalDate(item))}</small></a>):<p className="rh-muted">आगामी चाडपर्व विवरण अहिले उपलब्ध छैन।</p>}</div></section>
    <section className="rh-card"><header className="rh-card-head"><div><span className="rh-kicker">छिटो पहुँच</span><h2>दैनिक प्रयोग</h2></div></header><div className="rh-quick-grid"><a href="/rashifal"><b>♈</b><span>राशिफल</span></a><a href="/convert"><b>↔</b><span>मिति रूपान्तरण</span></a><a href="/tools/nepali-typing"><b>ने</b><span>नेपाली टाइपिङ</span></a><a href="/tools/voice-typing"><b>🎙</b><span>बोली टाइपिङ</span></a><a href="/time-machine"><b>⌛</b><span>समययन्त्र</span></a><a href="/on-this-day"><b>इत</b><span>आज इतिहासमा</span></a></div></section>
    <a className="rh-astro-teaser" href="/tools/astro"><span>विशेष उपकरण</span><strong>खगोलीय पात्रो</strong><small>चन्द्र अवस्था, तिथि र आकाशीय घटना छुट्टै अनुभवमा हेर्नुहोस्।</small></a>
   </aside>
  </div>
 </main>
}
